README.md

Here's a sample readme for your project with some basic formatting attached.

Added Readme.MD

---

patches/tModLoader/Terraria.ModLoader/ModPlayer.cs
patches/tModLoader/Terraria.ModLoader/PlayerHooks.cs
patches/tModLoader/Terraria/Player.cs.patch

Yay baby's first PR.
I'll test them in a bit after I get some sleep.

OnHitNPC and OnHitByNPC hooks for ModPlayer.

---

patches/tModLoader/Terraria.ModLoader/GlobalProjectile.cs
patches/tModLoader/Terraria.ModLoader/ModProjectile.cs
patches/tModLoader/Terraria.ModLoader/ProjectileLoader.cs
patches/tModLoader/Terraria/Projectile.cs.patch

returns null to do the vanilla check, true/false to override for ModProjectile (returns null by default)
(requested by Grox)
might be easier to add me as collaborator at this point I'm planning on doing more stuff

added Projectile.CanCutTiles hook

---

ExampleMod/Items/Banners/OctopusBanner.cs
ExampleMod/Items/CopperShortsword.cs
ExampleMod/Items/ExampleHamaxe.cs
ExampleMod/Items/ExampleQuestFish.cs
ExampleMod/Items/Weapons/ExampleBullet.cs
ExampleMod/Items/Weapons/ExampleLaserWeapon.cs
ExampleMod/Items/Weapons/ExampleSpear.cs
ExampleMod/Items/Weapons/ExampleSword.cs
ExampleMod/Items/Weapons/PurityTotem.cs
ExampleMod/Items/Weapons/SpectreGun.cs
ExampleMod/Items/Weapons/Wisp.cs
ExampleMod/Projectiles/ExampleBullet.cs

I added some comments for guiding the beginners.

Added comments to several example object

---

patches/tModLoader/Terraria.ID/MountID.cs.patch

Added consts for vanilla mount names for easier reference.

Add mount names to MountIDs

---

patches/tModLoader/Terraria/Main.cs.patch

Made rendertargets public.

---

patches/tModLoader/Terraria/WorldGen.cs.patch

Fixes #216

---

patches/tModLoader/Terraria.DataStructures/Point16.cs.patch

Adds the +, -, * and / operators for Point16 as well as 2 new constructors
Allows to do sum, subtract, multiply and divide with Point16 without the need to do e.g. `new Point16(first.X + second.X, first.Y + second.Y)`

Point16 operators

---

patches/tModLoader/Terraria.ModLoader.IO/TagSerializer.cs

Adds a Point16 TagSerializer.
Removes the need for modders to add it manually, which could result in errors if not handled properly.

Point16 serializer

---

patches/tModLoader/Terraria.Localization.Content.en-US.tModLoader.json

Added Russian Translation for all TML buttons and texts
Many russian people play with TML, this will make it easier for them to understand TML features.
Russian people will see every TML feature on Russian language and not on English.

Added proper Russian Translations for everything

---

patches/tModLoader/Terraria.Localization.Content.ru-RU.tModLoader.json

Added Russian translation for Mod Sources buttons

Added Russian translation for Mod Sources

---

patches/tModLoader/Terraria.Localization.Content.fr-FR.tModLoader.json

Added french translations

---

patches/tModLoader/Terraria.Localization.Content.zh-Hans.tModLoader.json

This PR is about translation of TML itself. It adds the Chinese translation for TML.
- It adds Chinese translation.
Same as section above.

Add Chinese translation.

---

patches/tModLoader/Terraria.Localization.Content.pl-PL.tModLoader.json

Added remaining Polish translation

---

patches/tModLoader/Terraria.Localization.Content.es-ES.tModLoader.json

Original forum post (containing some lines that aren't in the current file): https://forums.terraria.org/index.php?threads/1-3-tmodloader-a-modding-api.23726/page-945#post-1497855
I translated the few missing lines, and fixed and improved several others, often just small changes. I shortened some of them a bit so they fit in the boxes, and gave more fitting names to some concepts (notably, "re-actualizar" became "reiniciar", which would normally mean reset or restart, and in this context the meaning is clear).
The changes described above would hopefully make for a more natural and professional localization.
I worked on a big game translation project in the past, so this isn't a shot in the dark; be sure to find someone else to re-check if possible, though. I hope you decide to take these …

Suggested Spanish localization changes

---

patches/tModLoader/Terraria.Localization.Content.it-IT.tModLoader.json

The file was untouched, meaning that it was still in full english; I translated all of it into italian
I hope I translated all the necessary sections and possibly didn't screw up the code
So that Italian people can use tModLoader with more ease
I'm not sure, but it's possible that some of the text goes out of its bubble; in that case, I'll be happy to shorten it

Suggested tModLoader italian translation

---

solutions/ReleaseExtras/README_Linux.txt

Added some clarification on how to run the tModLoaderServer script
It didn't contain the information
Because it would probably help one or two people, I guess.
Less confused people
The readme file grows a few bytes, information might seem unnecessary 
Ease of life when running the server software

Added clarification on running script

---

ExampleMod/Tiles/MonsterBanner.cs

Allows banners to be placed on hammered platforms.

Fixes #384.

---

ExampleMod/ExampleAdvancedRecipe.cs

Adding ModRecipe inherited class example
Example for custom recipe requirements other than ingredients and tiles
Comments might be a little bad grammatically

Adding Advanced Recipe Example

---

patches/tModLoader/Terraria.ModLoader.UI/UIBuildMod.cs

Title.
This fixes this > https://i.imgur.com/cf5UfSI.png < crash I've mentioned in discord earlier.

Fixed filename-less compilation errors (like CS1704) crashing the game.

---

patches/tModLoader/Terraria.Localization.Content.zh-Hans.tModLoader.json
solutions/TranslationsNeeded.txt

Well, I'm glad I finally understand the "LoadErrorMajorVersionMismatch"......

 Update Chinese translation

---

patches/tModLoader/Terraria.ModLoader/Mod.cs
patches/tModLoader/Terraria.ModLoader/ModContent.cs

Fixed a seemingly typo in Mod.
N/A
N/A
Fixed a typo.
May break some other mod code that is using this api.
N/A
...

Typo? Mod.GetFileSteam -> Mod.GetFileStream

---

patches/tModLoader/Terraria.ModLoader.Default.Patreon/Orian.cs

Adding a method to hide the boots while wearing it.
I hope it's not the wrong place to put it.

hiding boots using the robes

---

patches/tModLoader/Terraria.ModLoader/MonoModHooks.cs

Currently, when creating a MonoMod Hook, tModLoader logs the target method's signature with the parameter types' real names, but most people don't use these (I've never seen `Single` or `Boolean` used in real code before). This PR also fixes types not showing up when they were ref/out.
Old:
`On.Terraria.Player::PickAmmo(Item, ref , ref , ref , ref , ref , Boolean)`
New:
`On.Terraria.Player::PickAmmo(Item, ref int, ref float, ref bool, ref int, ref float, bool)`
Use something other than a Dictionary for aliases? I don't know if it's really needed since people who use MonoMod probably know the types' real names anyways.
N/A
Fixes a problem.
Clearer and easier to understand.
I don't think there are any, really.
N/A
N/A

Modify MonoModHooks Method Signature

---

patches/tModLoader/Terraria.ModLoader/MusicWrappers.cs

Allows for music in the .ogg format to have internal loops. If the file has the tag `LOOPSTART`, the song will jump to the tag's value instead of the beginning once it reaches the end (or the value of `LOOPEND`, if specified).
N/A
Mods cannot do this on their own. At least, not without code injection.
Songs with intros can use `LOOPSTART` to stop the intro from playing more than once, and both `LOOPSTART` and `LOOPEND` can be used to give songs proper loops if they lack them.
N/A
Doesn't account for `LOOPSTART` being below 0 or higher than the song's length in samples, but 1. an exception is thrown if it is, and 2. why would it ever be set to either values?
N/A. The tags cannot be added via code.
This is my first pull request, so I hope I did everything correctly!

Allow for internal loops in .ogg files

---

ExampleMod/.editorconfig

Added the .editorconfig file to ExampleMod
N/A
To help contributors format ExampleMod appropriately
Contributors would now have an easier way to format contributions to ExampleMod 
I don't see any...
I don't see any...
N/A

ExampleMod editorconfig

---

ExampleMod/ExampleAdvancedRecipe.cs

Fixed issue with Main.npc loop, optimized checking for range code. Thx absoluteAquarian for pointing it out.

Fixed ExampleAdvancedRecipe

---

ExampleMod/Items/Weapons/ExampleFlail.cs

Removed Unnecessary Parameter in ExampleFlail

---

ExampleMod/Items/Weapons/ExampleSword.cs

Someone asked me to make an ExampleShortsword so I looked at the comments to see if it showed how and I noticed the comments were kinda wack so I changed them a bit.

Updated ExampleSword comments

---

patches/tModLoader/Terraria.ModLoader.UI/UICreateMod.cs

Removing unused stuff from the Mod file created in UICreateMod
Mods created beyond this will have that tiny bit less clutter
To keep the ctor and comment out the ModProperties and explain what they are.

Decluttered Mod in UICreateMod

---

ExampleMod/Tiles/ExampleSapling.cs

I cleaned some of the code in ExampleSapling and I added comments to the growing part of it because a friend asked me to :p
Users are able to understand code easier.

Cleaned code and added comments to ExampleSapling tile

---

.github/CONTRIBUTING.md
ExampleMod/ExampleConfig.cs
ExampleMod/ExampleWorld.cs

**Description of the Change**
Fixes a few typos in ExampleConfig, ExampleWorld and the contribution guidelines 
**Alternate designs**
n/a
**Why this should be merged into tModLoader**
Fixes misspellings
**Benefits**
See previous section.
**Possible drawbacks**
n/a
**Applicable Issues**
n/a
**Sample Usage**
n/a

Typo Fixes

---

patches/tModLoader/Terraria.ModLoader.Engine/GoGVerifier.cs

- Fixed GOG checks not working correctly when tML is not Terraria.exe;
- Added an error message for when the Content directory is missing;
- Cleaned up GoGCheck().

Fixed GOG checks not working correctly when tML is not Terraria.exe, etc

---

patches/tModLoader/Terraria.ModLoader.Core/ModCompile.cs

Fixes this silly error (introduced by #798) that's on the master branch right now: https://i.imgur.com/ikR7Sjm.png
Tested and working.

Fixed 'Missing dll reference: <dllName>.dll.dll' errors on build

---

setup/Setup/PatchTask.cs
setup/Setup/SetupOperation.cs

There's also protection against file attribute issues.
It's good enough for now? Won't clash with VS anymore.

Fixed UnauthorizedAccessExceptions in the setup tool by replacing directory deletion with wiping.

---

ExampleMod/Tiles/ExampleHerb.cs

Cleaned up ExampleHerb quite a bit. The original code looked really ugly so I tried to make it better

Sparkling ExampleHerb code

---

patches/tModLoader/Terraria/Player.cs.patch

Fixed ModPlayer.OnHitAnything() hook not being called.

---

patches/tModLoader/Terraria.Localization.Content/es-ES.tModLoader.json

Added the translation "aislando" and deleted an unnecesary word on other string, as well as deleting another unnecesary cap.

Update Spanish translation

---

patches/tModLoader/Terraria.Localization.Content/zh-Hans.tModLoader.json

Add missing comma
Add Chinese translations for #979
Use LF instead of CRLF line breaks

Update Chinese translation

---

patches/tModLoader/Terraria.Localization.Content/en-US.tModLoader.json
patches/tModLoader/Terraria.ModLoader.UI/Interface.cs

Addition to #958 
* Add dedicated server mod list
* Add dedicated server mod browser
* Add `MessageBoxShow` generated tip

Move more hardcoded strings to resource file

---

patches/tModLoader/ReLogic/tModLoader.xml
patches/tModLoader/Terraria/GameContent/Creative/ItemFilters.cs.patch
patches/tModLoader/Terraria/ID/ItemRarityID.cs
patches/tModLoader/Terraria/Item.cs.patch
patches/tModLoader/Terraria/Main.cs.patch
patches/tModLoader/Terraria/Player.cs.patch
patches/tModLoader/Terraria/PopupText.cs.patch
patches/tModLoader/Terraria/UI/ItemSlot.cs.patch
patches/tModLoader/Terraria/tModLoader.xml

:walking_paladin:
if I somehow missed something related to Master's unique Fiery Red rarity please let me know

tooltips, crits, and Fiery Red shenanigans

---

patches/tModLoader/Terraria/Main.cs.patch
patches/tModLoader/Terraria/UI/ItemSlot.cs.patch

I also fixed the issue where you would always buy two of something
there's a really dumb thing here where Journey dupe menu tooltips just decide to perish, I spent most of today trying to diagnose the issue but eventually I got tired of staring literally the entire tooltip method down the barrel so hey maybe someone smarter than me can diagnose this issue

tooltips but again

---

patches/tModLoader/Terraria/Item.cs.patch
patches/tModLoader/Terraria/Item_tML.cs
patches/tModLoader/Terraria/ModLoader/CommandManager.cs
patches/tModLoader/Terraria/ModLoader/Config/ConfigManager.cs
patches/tModLoader/Terraria/ModLoader/Core/ModCompile.cs
patches/tModLoader/Terraria/ModLoader/GlobalItem.cs
patches/tModLoader/Terraria/ModLoader/GlobalNPC.cs
patches/tModLoader/Terraria/ModLoader/GlobalProjectile.cs
patches/tModLoader/Terraria/ModLoader/IO/PlayerIO.cs
patches/tModLoader/Terraria/ModLoader/ItemLoader.cs
patches/tModLoader/Terraria/ModLoader/ModContent.cs
patches/tModLoader/Terraria/ModLoader/ModLoader.cs
patches/tModLoader/Terraria/ModLoader/ModNet.cs
patches/tModLoader/Terraria/ModLoader/NPCLoader.cs
patches/tModLoader/Terraria/ModLoader/PlayerHooks.cs
patches/tModLoader/Terraria/ModLoader/ProjectileLoader.cs
patches/tModLoader/Terraria/ModLoader/UI/DownloadManager/DownloadModFile.cs
patches/tModLoader/Terraria/ModLoader/UI/Interface.cs
patches/tModLoader/Terraria/ModLoader/UI/UIModItem.cs
patches/tModLoader/Terraria/ModLoader/UI/UIModSourceItem.cs
patches/tModLoader/Terraria/NPC.TML.cs
patches/tModLoader/Terraria/NPC.cs.patch
patches/tModLoader/Terraria/Player.TML.cs
patches/tModLoader/Terraria/Player.cs.patch
patches/tModLoader/Terraria/Projectile.TML.cs
patches/tModLoader/Terraria/Projectile.cs.patch

This PR implements #1062.
- ModWorld is never reinstanced, so it didn't need any work.
- I'm not sure if it's worth to check for indices being out of bounds in Try methods.

Implemented #1062 (Make Get/TryGet consistent across all of tML)

---

ExampleMod/Items/Weapons/ExampleGun.cs

A few extra comments in the SetDefaults, fixed a few typos

ExampleGun comments

---

ExampleMod/Common/ExamplePlayerDrawLayer.cs

For some reason this wasn’t done already. This just updates the file to use the new OOP model.

update Example Player Draw Layer

---

patches/tModLoader/Terraria/Player.cs.patch
patching_todo.txt

added missing ItemLoader.ConsumeItem

---

patches/tModLoader/Terraria/Main.cs.patch
patches/tModLoader/Terraria/ModLoader/Engine/GoGVerifier.cs
patches/tModLoader/Terraria/ModLoader/Engine/Steam.cs

Fix typo that prevented assets from being loaded

---

ExampleMod/Common/GlobalNPCs/ProjectileModificationGlobalNPC.cs
ExampleMod/Common/GlobalProjectiles/ExampleProjectileModifications.cs
ExampleMod/Content/Items/Weapons/ExampleModifiedProjectilesItem.cs

Adds some stuff showcasing how to modify shot projectiles. Related to the issue I recently made.
Probably not, but add some if you need to.

[1.4] ExampleMod Commit showcasing projectile modification.

---

patches/tModLoader/Terraria/ModLoader/ModTile.cs
patches/tModLoader/Terraria/ModLoader/TileLoader.cs
patches/tModLoader/Terraria/SceneMetrics.cs.patch
patching_todo.txt

Too lazy to add anything proper. I didn't actually readd the `closer` bool because vanilla properly split it up now.

Readded TileLoader.NearbyEffects

---

patches/tModLoader/Terraria/ModLoader/Core/ModCompile.cs

Quick lil thing, I'm surprised no one did it earlier.

Cherry pick VS 16.8 command line hotfix

---

ExampleMod/Common/ExamplePlayerDrawLayer.cs
ExampleMod/Content/Items/Consumables/ExampleLifeFruit.cs
ExampleMod/Content/Items/Consumables/PlanteraItem.cs
ExampleMod/Content/Tiles/ExampleOre.cs

EM doesn't compile
Changed `Before` to `BeforeParent`, `bool UseItem` to `bool? UseItem`, and `ModWorld` to `ModSystem`
no

Make EM compile (1.4_mergedtesting)

---

patches/tModLoader/Terraria/Item.cs.patch

There are a few "DefaultToXX" methods in Item.cs such as DefaultToBow, DefaultToRangedWeapon etc. But unfortunally, they are private. This PR makes them the public. These may help modders while setting defaults to their items.

Made "DefaultToXX" in Item.cs Publicization

---

.github/CONTRIBUTING.md

Added hyperlink and subsection regarding checking style and formatting prior to contributing.
Points to our existing style guide; could not find any other pointer to style guide in our contributing checks Wiki.

Include "You follow our style guide" in Contributing checks

---

.github/workflows/build.yml

This PR is just confirming that PRs trigger the push event. The code changes build ExampleMod

build ExampleMod on push

---

patches/Terraria/Terraria/UI/FancyErrorPrinter.cs.patch

Begone, Cursed Patch!

---

patches/tModLoader/Terraria/Localization/Content/es-ES/tModLoader.json

Added the boss bar interface translation.

[1.4] Spanish localization update

---

ExampleMod/Common/Systems/SimpleDataAtParticularLocations.cs

A NullReferenceException in ExampleMod due to misplaced code/
Moved the code to where it should be.
No

Fixed ExampleMod data saving

---

patches/tModLoader/Terraria/GameContent/SmartCursorHelper.cs.patch

This allows modded torches to be placed by smart cursor without any extra work from the modder.
There is an issue for it: #1383 
There really is no reason that modders should have to do this themselves as it is an easy fix on the tModLoader side.
None other than forcing modders to do it themselves.
The only thing that modders have to do to use this new feature is put `TileID.Sets.Torch[Type] = true;` in their torch's SetDefaults method which they should already be doing.
None

Allow modded torches to support smart cursor

---

ExampleMod/Common/GlobalItems/ShortswordGlobalItem.cs
ExampleMod/Common/GlobalNPCs/ExampleNPCLoot.cs
ExampleMod/Content/Items/Weapons/ExampleModifiedProjectilesItem.cs
ExampleMod/Content/Items/Weapons/ExampleShootingSword.cs
ExampleMod/Content/Items/Weapons/ExampleShotgun.cs
ExampleMod/Content/NPCs/MinionBoss/MinionBossBody.cs
ExampleMod/Content/NPCs/Worm.cs
ExampleMod/Content/Pets/ExampleLightPet/ExampleLightPetBuff.cs
ExampleMod/Content/Pets/ExamplePet/ExamplePetBuff.cs
ExampleMod/Content/Projectiles/ExampleCloneProjectile.cs

Example Mod Compilation Errors after 1.4.2
Fixed compilation errors resulting from method parameter changes.
No?

Fix example mod 1.4.2 

---

patches/Terraria/Terraria/Audio/MP3AudioTrack.cs.patch
patches/Terraria/Terraria/Terraria.csproj.patch
patches/tModLoader/Terraria/Audio/LegacyAudioSystem.cs.patch
patches/tModLoader/Terraria/Main.cs.patch
patches/tModLoader/Terraria/MessageBuffer.cs.patch
patches/tModLoader/Terraria/NetMessage.cs.patch
patches/tModLoader/Terraria/Player.cs.patch
patches/tModLoader/Terraria/Terraria.csproj.patch
setup/app.config

Updated the patches to 1.4.2.1
Builds on my computer

Update patches to 1.4.2.1

---

patches/Terraria/Terraria/Audio/LegacyAudioSystem.cs.patch
patches/Terraria/Terraria/Audio/MP3AudioTrack.cs.patch
patches/Terraria/Terraria/Audio/SoundEngine.cs.patch
patches/Terraria/Terraria/Audio/SoundPlayer.cs.patch
patches/Terraria/Terraria/Terraria.csproj.patch
patches/tModLoader/Terraria/Audio/LegacyAudioSystem.cs.patch
patches/tModLoader/Terraria/Audio/LegacySoundPlayer.cs.patch

Did an oopsie and now it should be fixed

Fix patches

---

patches/tModLoader/Terraria/Localization/Content/es-ES/tModLoader.json

Added new string from the English lang file (l. 348)

[1.4] Update tModLoader.json

---

patches/tModLoader/Terraria.Localization.Content/pt-BR.tModLoader.json

Test for now
template=localization

Brazilian Portuguese localization addition

---

patches/tModLoader/Terraria/ModLoader/Config/EntityDefinition.cs
patches/tModLoader/Terraria/ModLoader/Config/UI/ItemDefinitionElement.cs

Rehashes: https://github.com/tModLoader/tModLoader/pull/1467 with less changes to bring to working.
Going to ask Kitten to rework to check & address other elements, maybe?

Fix ItemDefinitions for ModConfig

---

patches/tModLoader/Terraria/ModLoader/Default/UnloadedNonSolidTile.cs
patches/tModLoader/Terraria/ModLoader/Default/UnloadedSemiSolidTile.cs
patches/tModLoader/Terraria/ModLoader/Default/UnloadedSolidTile.cs
patches/tModLoader/Terraria/ModLoader/Default/UnloadedSupremeFurniture.cs

#1556 
Fixed anchoring resulting from the Style1x1 usage.

Fix unloaded Tile breaking

---

patches/tModLoader/Terraria/Program.cs.patch
patches/tModLoader/Terraria/Social/Steam/WorkshopHelper.TML.cs

Also update workshop query to formally skip non-public workshop items.

Restore Launch Game, update comments

---

patches/tModLoader/Terraria/ModLoader/UI/ModBrowser/UIModBrowser.cs
patches/tModLoader/Terraria/ModLoader/UI/UIModSourceItem.cs
patches/tModLoader/Terraria/Social/Steam/WorkshopHelper.TML.cs
patches/tModLoader/Terraria/Social/Steam/WorkshopSocialModule.TML.cs

#1631 
Updated WorkshopHelper CheckWorkshop Connection to ensure public items are accounted for IF there are public items.
Also fixed a System.Version crash encountered.

Fix #1631 and a Version string issue

---

patches/tModLoader/Terraria/Main.cs.patch
patches/tModLoader/Terraria/ModLoader/Logging.cs
patches/tModLoader/Terraria/MonoLaunch.cs.patch

Fix Mouse Scaling being doubled in FNA & LaunchParams Logging

---

patches/tModLoader/Terraria/GameContent/UI/States/UIWorldLoad.cs.patch
patches/tModLoader/Terraria/ModLoader/Logging.cs
patches/tModLoader/Terraria/ModLoader/UI/UIModSourceItem.cs
patches/tModLoader/Terraria/Properties/launchSettings.json.patch
patches/tModLoader/Terraria/Social/Base/WorkshopIssueReporter.cs.patch
patches/tModLoader/Terraria/Social/Steam/WorkshopHelper.TML.cs
patches/tModLoader/Terraria/Social/Steam/WorkshopHelper.cs.patch
patches/tModLoader/Terraria/Social/Steam/WorkshopSocialModule.TML.cs
solutions/ReleaseExtras/RuntimeFiles/InstallNetFramework.sh

1.4 command line publish solxan

---

patches/tModLoader/Terraria/Player.cs.patch

#1695 
I found out that releaseUseItem was the culprit, it was set after the hammer use due to useItemFix, so I fixed it, verifying that the order of the other things using it was preserved according to vanilla
I don't think so, unless someone manages to understand how releaseUseItem is intended to work, I will stick to how vanilla works

Hammer fix

---

solutions/ReleaseExtras/RuntimeFiles/start-tModLoader.bat
solutions/ReleaseExtras/RuntimeFiles/start-tModLoaderServer.bat

Add flow through of Steam Launch Args

---

patches/tModLoader/Terraria/Localization/Content/zh-Hans/tModLoader.json

Update Chinese localization

---

patches/tModLoader/Terraria/Localization/Content/pt-BR/tModLoader.json

Translated the new strings + fixed a little mistake.

[1.4] Update Brazilian Portuguese localization 

---

patches/tModLoader/Terraria/Graphics/Light/LightMap.cs.patch

Fix SetSize on LightMap.cs for Higher Resolutions #1661

---

patches/tModLoader/Configuration.targets.patch
solutions/CompleteLib.bat
solutions/buildDebug.bat
solutions/buildRelease.bat

1) Add clearing of all nuget cache to the build scripts
2) Remove 'refs' folder from output of build

Try A Few Google Fixes for Build Error

---

solutions/ReleaseExtras/RuntimeFiles/InstallNetFramework.sh
solutions/ReleaseExtras/RuntimeFiles/start-tModLoaderServer.sh

Some fixes to the unix launch scripts based on Javid's issue about Debian Stretch.

[1.4] UNIX script POSIX-compliancy fixes

---

patches/tModLoader/Terraria/ModLoader/ModContent.cs
patches/tModLoader/Terraria/ModLoader/MonoModHooks.cs
patches/tModLoader/Terraria/ModLoader/UI/Interface.cs
patches/tModLoader/Terraria/Program.TML.cs
patches/tModLoader/Terraria/Program.cs.patch
solutions/ReleaseExtras/RuntimeFiles/InstallNetFramework.bat
solutions/ReleaseExtras/RuntimeFiles/InstallNetFramework.sh
solutions/ReleaseExtras/RuntimeFiles/start-tModLoader.bat
solutions/ReleaseExtras/RuntimeFiles/start-tModLoaderServer.bat

Reverts tModLoader/tModLoader#1852
Needs more testing

Revert "Many Misc Tiny Fixes"

---

patches/tModLoader/Terraria/ModLoader/Logging.cs
solutions/ReleaseExtras/RuntimeFiles/InstallNetFramework.bat
solutions/ReleaseExtras/RuntimeFiles/start-tModLoader.bat
solutions/ReleaseExtras/RuntimeFiles/start-tModLoaderServer.bat

And a change in a file so triggers rebuild

Revert InstallNetFramework.bat changes in previous build

---

patches/tModLoader/Terraria/GameInput/PlayerInput.cs.patch

Update PlayerInput.cs.patch to fix button binding

---

patches/tModLoader/Terraria/GameContent/Tile_Entities/TEHatRack.TML.cs

Fix hat rack TE

---

patches/tModLoader/Terraria/ModLoader/IO/TileIO_TEs.cs

Fix compiler error introduced by #1885

[1.4] Fix compilation error

---

patches/tModLoader/Terraria/Item.TML.cs
patches/tModLoader/Terraria/Item.cs.patch
patches/tModLoader/Terraria/Main.TML.cs
patches/tModLoader/Terraria/Main.cs.patch
patches/tModLoader/Terraria/MessageBuffer.cs.patch
patches/tModLoader/Terraria/Netplay.cs.patch
patches/tModLoader/Terraria/Player.TML.cs
patches/tModLoader/Terraria/Player.cs.patch
patches/tModLoader/Terraria/Recipe.cs.patch

Move some methods into partials
Fix XML comment in `Item.TML.cs`
Instead of deleting a bunch of lines in `Main`, comment them
Remove unused field and methods from `Netplay`
Slightly cleanup `Recipe` patch
Update `TerrariaHooks.dll`

[1.4] Patch and general cleanup

---

patches/tModLoader/Terraria/ModLoader/Config/UI/ItemDefinitionElement.cs
patches/tModLoader/Terraria/ModLoader/Config/UI/NPCDefinitionElement.cs
patches/tModLoader/Terraria/ModLoader/Config/UI/PrefixDefinitionElement.cs
patches/tModLoader/Terraria/ModLoader/Config/UI/ProjectileDefinitionElement.cs

Bad check inside an if condition
Fix it
`XLoader.TryGetX`

[1.4] Fix if check

---

ExampleMod/Projectiles/Minions/ExampleSimpleMinion/ExampleSimpleMinion.cs

Removes reduntant variable and its related checks in targeting, making it easier to understand.
Also rearranges target finding logic to improve performance by moving a line-of-sight check.
No.

ExampleSimpleMinion Simplification
