tModLoader/tModLoader

- patches/tModLoader/Terraria.ModLoader/Mod.cs
- patches/tModLoader/Terraria.ModLoader/ModLoader.cs
- patches/tModLoader/Terraria.ModLoader/ModSound.cs
- patches/tModLoader/Terraria.csproj.patch
Custom sounds for items support.  Changes to .tmod file format to
include .wav files. Load in a sound file by using and empty class
extending ModSound. Wav files should be stereo, 16 bit pcm, 44100 hz.
Also, auto copy built Terraria to Steam folder.
> Sound Support

- patches/tModLoader/Terraria.ModLoader/ModMountData.cs
- patches/tModLoader/Terraria.ModLoader/MountLoader.cs
- patches/tModLoader/Terraria/Mount.cs.patch
- patches/tModLoader/Terraria/Player.cs.patch
still working out the bugs that are caused by the vanilla version not having many mounts, so everything is case sensitive in the vanilla.
> Added UseAbility and AimAbility

- patches/tModLoader/Terraria/Player.cs.patch
The return value of TileLoader.Slope was being ignored and the Y-coordinate passed to TileLoader.Slope was incorrect (it was the X-coordinate).
This should fix those two bugs.
> Fixed two TileLoader.Slope bugs

- patches/tModLoader/Terraria.ModLoader/GlobalItem.cs
- patches/tModLoader/Terraria.ModLoader/ItemLoader.cs
- patches/tModLoader/Terraria.ModLoader/ModItem.cs
- patches/tModLoader/Terraria/Main.cs.patch
item.whoAmI is not being set, thus animations sped up eachother when
done via draw hooks because they'd all use the same index (0). Fixed
with a whoAmI parameter.
> Pre/Post draw hooks for items whoAmI fix

- patches/tModLoader/Terraria.ModLoader/EquipTexture.cs
- patches/tModLoader/Terraria.ModLoader/GlobalItem.cs
- patches/tModLoader/Terraria.ModLoader/ItemLoader.cs
- patches/tModLoader/Terraria.ModLoader/ModItem.cs
- patches/tModLoader/Terraria/Player.cs.patch
ItemLoader.WingUpdate now returns a bool value.
Other classes that have WingUpdate now have a "NewWingUpdate" method that returns a bool value. (Calls the old WingUpdate and returns false by default for backward compatibility.)
Player.Update has a new local variable "isCustomWings" that gets the return value from ItemLoader.WingUpdate, and uses it to stay out of 3 if/else/else if blocks that play sounds or manipulate wing animations.
WingSpeeds methods (Vertical and Horizontal) have overloaded versions that also pass the player as a parameter. In stock code, the player parameter is used to get control status for jetpacks and hoverboards, as well as manipulate vertical velocity for hovering. (New overloaded version calls the old version by default for backward compatibility.)
> Fixes to WingUpdate and WingSpeeds (Resolves #87)

- patches/tModLoader/Terraria.ModLoader/GlobalTile.cs
- patches/tModLoader/Terraria.ModLoader/GlobalWall.cs
- patches/tModLoader/Terraria.ModLoader/ModTile.cs
- patches/tModLoader/Terraria.ModLoader/ModWall.cs
- patches/tModLoader/Terraria.ModLoader/ModWorld.cs
- patches/tModLoader/Terraria.ModLoader/TileLoader.cs
- patches/tModLoader/Terraria.ModLoader/WallLoader.cs
- patches/tModLoader/Terraria.ModLoader/WorldHooks.cs
- patches/tModLoader/Terraria/Main.cs.patch
- patches/tModLoader/Terraria/Player.cs.patch
I've added two new hooks:
`PlaceInWorld`, a hook/callback for placing tiles into the world which passes the tile coordinates and Item stack used.
Additionally, I've added a `PostDrawTiles` hook for `ModWorld` which would allow users to draw their own systems similar to Terraria's wiring system without drawing above of items, npcs, and UIs.
> Add PlaceInWorld and PostDrawTiles hooks.

- ExampleMod/Items/Weapons/PurityTotem.cs
- ExampleMod/Projectiles/Minions/HoverShooter.cs
- ExampleMod/Projectiles/Minions/PurityWisp.cs
In Terraria 1.3.4, there is a new feature which allows minions to target specific NPCs. You can right-click with any summon weapon and it locks on to the nearest enemy. However, the custom AI in Example Mod's HoverShooter class doesn't take advantage of that.
I wanted to fix that so that other modders can see how it works.
> (ExampleMod) Allow 1.3.4 minion targetting for HoverShooter.

- patches/tModLoader/Terraria.ModLoader/Mod.cs
- patches/tModLoader/Terraria.ModLoader/ProjectileLoader.cs
I have noticed that when player is killed by mod projectile, it actually throw an IndexOutOfRange error which leads to no death text would be shown. I'd like to fix this bug by adding the hook for `Main.projName`.
> Fixed the bug when player is killed by mod projectile

- patches/tModLoader/Terraria.ModLoader/ErrorLogger.cs
This overload allows the user to log objects, it simply retrieves methods, constructors, fields and properties in them.
(Fields and properties have their name AND value get retrieved)
I tested this and it should work, tell me if you get any errors/exceptions
> Add object overload for ErrorLogger.Log

- .editorconfig
Adds a `.editorconfig` file which will make some editors automatically follow the formatting rules outlined in `CONTRIBUTING.md`
Can't hurt and it saves headaches from having to reconfigure editors.
http://editorconfig.org/
> Adds a .editorconfig

- installer2/LinuxInfo.java
- solutions/ReleaseExtras/README_Linux.txt
Newer Steam installations under Linux change the installation path.  The tModLoader installer can now handle the new path (in addition to the two previous paths already handled).
At first, I made a patchset (now revoked) that mimic'd the file's format more closely.  I feel that adding support for the new path in the previous format made the code unwieldy.  I feel that this solution is superior.
Users with newer Steam installations should be able to install tModLoader as easily as possible.
This patch makes tModLoader easier to use for more people.
None that I can see.
I did not test the XDG_DATA_HOME variant as I am unfamiliar with that setup.  But I am confident that the code flow for that variant remains unchanged.
N/A
> Account for newer Steam path in Linux installer

- patches/tModLoader/Terraria.ModLoader/NPCLoader.cs
PostDraw method is called PreDraw for GlobalNPCs, fixed to call PostDraw as expected.
> Fix NPCLoader calling PreDraw method in PostDraw

- patches/tModLoader/Terraria/Main.cs.patch
Added the object overload for Main.NewText
Removes the need to call object.ToString manually
> Object overload for Main.NewText

- .editorconfig
Visual Studio 2017 has its own supported settings for different languages. These four settings will enforce new lines before opening braces and `else`/`catch`/`finally` statements. I tested these in VS2017 15.2 and they work as intended. There's a smaller list of supported settings on the [Roslyn GitHub](https://github.com/dotnet/roslyn/blob/master/.editorconfig) and a longer one without descriptions on the [EditorConfigLanguage GitHub](https://github.com/madskristensen/EditorConfigLanguage/issues/10#issuecomment-310120306).
> .editorconfig enforces new line settings

- patches/tModLoader/Terraria.ModLoader.UI/UIModBrowser.cs
This pull request resolves #232 as requested by @JavidPack.  As @Chicken-Bones mentioned, duplicate mods still display in the mods menu and instead an error is thrown on loading and the duplicate mods are disabled (already implemented, not by me).  Pretty quick change, just thought I'd go ahead and push it since there hadn't been any work on this issue in a few days.
Proposed version was selected based on discussion as seen in #232.
Simple, quick fix for issue as requested by @Jofairden.
Better management of situations where an internal mod name is not distinct.
#232
> Resolves #232

- patches/tModLoader/Terraria.GameContent.UI.Elements/UIKeybindingListItem.cs.patch
- patches/tModLoader/Terraria.GameContent.UI.States/UIManageControls.cs.patch
- patches/tModLoader/Terraria.GameInput/PlayerInput.cs.patch
- patches/tModLoader/Terraria.GameInput/PlayerInputProfile.cs.patch
- patches/tModLoader/Terraria.GameInput/TriggerNames.cs.patch
- patches/tModLoader/Terraria.GameInput/TriggersSet.cs.patch
- patches/tModLoader/Terraria.Localization.Content.en-US.tModLoader.json
- patches/tModLoader/Terraria.UI/UIElement.cs.patch
- patches/tModLoader/Terraria.UI/UserInterface.cs.patch
- patches/tModLoader/Terraria/Main.cs.patch
This adds support for the middle mouse button and two extra mouse buttons (mouse 4 and 5).
Terraria lacks support for extra mouse buttons, which limits the ability of the game's UI.
This change will allow people to create mods that can use the middle and extra mouse buttons for any reason, whether in a UIElement, an item, etc.
There should hopefully not be any outside of an increased executable size.
Just like with the left and right mouse buttons, you can assign event handlers for the new buttons in a custom UIElement:
```csharp
base.OnMiddleClick += new UIElement.MouseEvent(this.OnMiddleClickMethod);
base.OnXButton1Down += new UIElement.MouseEvent(this.OnXButton1DownMethod);
base.OnXButton2Up += new UIElement.MouseEvent(this.OnXButton2UpMethod);
```
Override them:
```csharp
public …
```
> Added middle mouse, xbutton1, and xbutton2 support

- ExampleMod/Items/Weapons/ExampleSword.cs
- patches/tModLoader/Terraria.ModLoader/GlobalItem.cs
- patches/tModLoader/Terraria.ModLoader/ItemLoader.cs
- patches/tModLoader/Terraria.ModLoader/ModItem.cs
- patches/tModLoader/Terraria/Item.cs.patch
- patches/tModLoader/Terraria/Main.cs.patch
- patches/tModLoader/Terraria/Player.cs.patch
**Added** a ReforgePrice hook available to adjust the reforge pricing. The `reforgePrice` can be changed to override the price, `canApplyDiscount` can be set to false to never apply discount. Returning false will stop the vanilla pricing to take place and the price will be set to `reforgePrice`. The passed `reforgePrice` is `item.value` (as Terraria uses that as the base price). Returns true by default so vanilla pricing takes place. This hook will be useful to adjust reforge pricing without touching the actual item value.
**Adjusted** the PreReforge hook to return a bool.  Returns whether the reforge will take place. If false is returned, the PostReforge hook is never called because the reforge will not happen. Returns true by default.
**Changed** the reforge code slightly so any modded …
> Reforge hooks updates

- patches/tModLoader/Terraria.ModLoader/ItemLoader.cs
As the title says, this change allows thrown weapons to have prefixes. This change only affects non-stacked thrown weapons as _GeneralPrefix(item)_ already checks for _item.maxStack_ being 1.
This makes it more like how vanilla handles prefixes for weapons like the Bone Glove, which receives ranged prefixes. 
The fact that it allows prefixes on thrown weapons.
Mods that add these weapons would have to rebalance them to accommodate the potential for increased stats.
> Allows thrown weapons to have prefixes

- patches/tModLoader/Terraria/Player.cs.patch
Fixes an error that causes torches to duplicate and appear in the wrong position when thrown.
Also adds capability for other vanilla torches, aswell as modded torches, to be thrown the same way.
I first considered [this way](https://github.com/Leemyy/tModLoader/tree/torchThrowFix) of addressing the issue. But I decided that it was an inferior solution, since it would require each mod to manually add each of their torches to `ItemID.Sets.Torches`.
There is no way for a mod to realize the implemented behaviour.
Modded torches (and other vanilla torches) will be able to be thrown individually, just like the standard vanilla torch.
Negligibly worse performance of `Player.DropSelectedItem`.
> Fixes error when throwing torches

- patches/tModLoader/Terraria.Initializers/LaunchInitializer.cs.patch
User will be able to specify which player and world they want to launch with -skipselect launch option. When either one of the fields is invalid/empty, it will choose the default player/world (meaning first in the list).
Adds the ability to specify which player/world is used for debugging.
`-skipselect "Itorius:TestWorld"`
> skipselect now takes in player and world name

- patches/tModLoader/Terraria.Graphics.Effects/OverlayManager.cs.patch
- patches/tModLoader/Terraria/Main.cs.patch
`Overlays.Scene` is a vanilla feature that allows drawing overlays onto the screen at several points during the rendering process. Vanilla currently uses this to to draw the Sandstorm overlay and the Blizzard overlay.
However, as soon as you add an Overlay to `Overlays.Scene`, that uses `RenderLayers` other than `Landscape` or `All`, the game will crash. This happens because `OverlayManager.Draw(...)` calls `SpriteBatch.Begin(...)` even when End has not yet been called.
This change prevents that crash by only calling `SpriteBatch.Begin(...)` inside of `OverlayManager.Draw(...)` when the SpriteBatch is inactive at that point in the rendering process. It makes use of a default parameter to keep the codes changes as small as possible.
This effectively allows one to draw arbitrary data after …
> Overlays no longer crash the game

- patches/tModLoader/Terraria/Main.cs.patch
The buff tooltip needs to be offset by the height of the buff name, not by its own height.
This is technically a vanilla bug, but vanilla does not have multiline buff tooltips, so it never has a visual impact.
The buff name could be passed, instead of just its height, but this would just result in more code without any real benefit. It would also mean that the dimensions of the buff name will have to be calculated twice.
Multiline buff tooltips will get drawn properly. (See linked Issue for details)
None, as far as I can tell.
#318
> Offset buff tooltip properly, fixes #318

- patches/tModLoader/Terraria.ModLoader.Default/MysteryGlobalItem.cs
GlobalItem data will no longer be lost when an Item is loaded without the GlobalItem's Mod active.
Judging by how simple this change is, it seems like a typo of sorts. I did several tests to make sure I am not overlooking something, but all GlobalItems seem to get recovered properly. Even after several reloads without the Mods activated, all GlobalItems were recovered.
I first considered extracting the contents of `MysteryGlobalItem.data` in `ItemIO.SaveGlobals(Item item)` and to append them directly to the TagCompound. I opted for this instead, because it is a much simpler change.
It fixes part of a known issue.
#265
> Recover GlobalItem data through unload

- patches/tModLoader/Terraria/Main.cs.patch
- patches/tModLoader/Terraria/MessageBuffer.cs.patch
- patches/tModLoader/Terraria/Netplay.cs.patch
Before I go into detail on this change, [here's a video](https://youtu.be/YE0Qr5y36A8) to illustrate it more clearly.
When connecting to a server, vanilla will eventually send message 8 (`MessageID.RequestTileData`). This will prompt the server to send tile information, aswell as various game objects to the client. This includes all projectiles that are considered pets or have `netImportant` set to true (MessageBuffer:720). However, when connecting to a server, the pets/summons of other players will not show up unless they are re-summoned.
This has to do with the way the world is loaded on the client. While the data is being transmitted to the client, it will still perform regular updates. Because of this, summons, pets, and some other entities will get updated before their associated …
> Ensure the world is fully loaded before updating entities

- ExampleMod/Items/Infinity.cs
- ExampleMod/NPCs/ExampleChestSummon.cs
- patches/tModLoader/Terraria.ModLoader/ModPlayer.cs
- patches/tModLoader/Terraria.ModLoader/PlayerHooks.cs
- patches/tModLoader/Terraria/Main.cs.patch
- patches/tModLoader/Terraria/Player.cs.patch
* **Added**:
* **ModPlayer UpdateAutopause hook**: allows doing things in single player when the game is paused due to the autopause option being on.
* Usage example of the hook to Example Mod.
* **Changed**:
* In Player.TileInteractionsCheckLongDistance, added a check if the tile is active.
* ExampleMod ExampleChestSummon.ChestItemSummonCheck to match the vanilla mimic's checks.
* Without the UpdateAutopause hook, some bugs related to the autopause option being on can't be fixed properly.
* Without the check in Player.TileInteractionsCheckLongDistance, tiles could show hover info even if they weren't active. In vanilla, this was really only noticeable when using chests to spawn mimics from keys.
* Without the change in ChestItemSummonCheck, spawning the NPC from a modded chest would …
> UpdateAutopause hook

- patches/tModLoader/Terraria.Localization.Content.de-DE.tModLoader.json
- patches/tModLoader/Terraria.Localization.Content.en-US.tModLoader.json
- patches/tModLoader/Terraria.Localization.Content.es-ES.tModLoader.json
- patches/tModLoader/Terraria.Localization.Content.fr-FR.tModLoader.json
- patches/tModLoader/Terraria.Localization.Content.it-IT.tModLoader.json
- patches/tModLoader/Terraria.Localization.Content.pl-PL.tModLoader.json
- patches/tModLoader/Terraria.Localization.Content.pt-BR.tModLoader.json
- patches/tModLoader/Terraria.Localization.Content.ru-RU.tModLoader.json
Changed tModLoader localization line **LoadErrorUnknownXNBFileHint** to use `{0}` instead of `{path}`.
Currently, having an unknown XNB file will cause the following error:
```
Silently Caught Exception: Input string was not in a correct format.   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)   at Terraria.ModLoader.ModCompile.<>c.<ActivateExceptionReporting>b__15_0(Object sender, FirstChanceExceptionEventArgs exceptionArgs)
at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
at Terraria.Localization.LanguageManager.GetTextValue(String key, Object arg0)
at …
```
> Fixes crash when loading unknown .xnb files

- patches/tModLoader/Terraria.ModLoader/PlayerHooks.cs
- patches/tModLoader/Terraria/Player.cs.patch
* Prevents the carrot from the Collector's Edition version of Terraria from replacing the item on the fourth slot on the hotbar on character creation after the SetupStartInventory hook is called.
#347
> Collector's Edition Fix

- patches/tModLoader/Terraria/Main.cs.patch
Forces the graphics profile into HiDef if the graphics device supports it.
Not applicable
Allows mods to utilize SM3 shaders and other HiDef features if graphics device supports it.
SM3 shaders!
None
#488 
```cs
Effect shader = null;
if (graphics.GraphicsProfile == GraphicsProfile.HiDef)
shader = new Effect(graphics.GraphicsDevice, sm3ByteCode);
else // Device could not start HiDef, fallback to sm2 shader
shader = new Effect(graphics.GraphicsDevice, sm2ByteCode);
```
> Forces HiDef if grahpics device supports it

- patches/tModLoader/Terraria.ModLoader/ModCompile.cs
When a mod was compiled with both noCompile == true and editAndContinue == true in build.txt, ModCompile did not save the editAndContinue flag to the .tmod file. This change makes ModCompile save the editAndContinue flag as long as the mod has a Windows.pdb file.
N/A
Edit-and-continue speeds up the development cycle. It makes sense for modders who have to use noCompile == true to be able to use it, especially since the change required is minimal.
Modders who need to use noCompile == true will be able to use edit-and-continue.
N/A
Commit 30231fdb80195a5a6014b0fb3cd4b8865fa05f15 disables edit-and-continue in AssemblyManager for all users. Since the disabling appears to be temporary while related, active development is done, I tested my changes by re-enabling edit-and-continue locally. They …
> Allow mods which have noCompile == true to enable editAndContinue in build.txt

- ExampleMod/ExampleMod.cs
- ExampleMod/NPCs/ExamplePerson.cs
- patches/tModLoader/Terraria.ModLoader/GlobalNPC.cs
- patches/tModLoader/Terraria.ModLoader/ModNPC.cs
- patches/tModLoader/Terraria.ModLoader/NPCLoader.cs
- patches/tModLoader/Terraria/Wiring.cs.patch
* Adds `GoToKingStatue` and `GoToQueenStatue` methods to `ModNPC` and `GlobalNPC`, which lets modders allow NPCs to be teleported to the King or Queen statues when triggered.
* Adds `OnGoToStatue` method to `ModNPC` and `GlobalNPC`, which allows adding effects when an NPC teleports to an statue.
* Also removes the limit to the amount of town NPCs each statue can support (used to be 10). Normally, if there are more than 10 of the NPCs a King/Queen statue can teleport, only the first 10, ordered by their slot in the NPCs array, can teleport to the statue.
Check `ExamplePerson` for a sample usage of this change.
> King and Queen statues compatibility

- patches/tModLoader/Terraria.ModLoader/GlobalItem.cs
- patches/tModLoader/Terraria.ModLoader/ItemLoader.cs
- patches/tModLoader/Terraria.ModLoader/ModItem.cs
- patches/tModLoader/Terraria/Player.cs.patch
Made it so GlobalItem/ModItem PickAmmo receives the item that's using the ammo as an argument, and made the old methods obsolete.
Given that the item using the ammo is important when deciding which projectile to shoot from the weapon in some cases, like flame throwers and rocket launchers in vanilla, not having that as an argument for the aforementioned methods looks like an oversight. Although most of the time the item using the ammo is the item being held by the player, it is still better to have said item as an argument for a better understanding of the method's usage.
> Small Fix to GlobalItem/ModItem PickAmmo

- patches/tModLoader/Terraria.ModLoader.IO/ItemIO.cs
Just a quick fix to prevent crashes on save.
However prefixes that would normally crash are instead ignored and discarded.
Example of crash:
1: Set a prefix on an item >83 and >ModPrefix defined max, such as 255.
2: Exit the world and you'll crash to desktop without a message when saving is done.
3: You can still load the world and character, but regardless if you have the offending mod loaded or not, it will still crash on exit save.
My mod, Item Qualities and Durability used to set a prefix of 255 if the prefix is 0 to trick the tooltips in displaying stat changes when the item's quality changes. However it seems since ModPrefix was added, it would just crash like this.
Either way, said mod will be using a different way of doing this rather than the invalid prefix method.
> Fixes a NRE crash if an item has a prefix > 83 but no ModPrefix

- patches/tModLoader/Terraria.ModLoader.IO/WorldIO.cs
* Prevents the modded angler quest loading code from running if there was no modded angler quest saved on the previous session, which could only mean a vanilla quest was saved.
* The actual culprit was the call to `Main.AnglerQuestSwap()` at the end of the modded quest loading method, which should have only run when the item saved belonged to a mod that was not loaded or when the item was removed from said mod.
> Fix vanilla angler quests reseting on world reload

- ExampleMod/Items/Weapons/ExampleMagicMissile.cs
- patches/tModLoader/Terraria.ModLoader/CombinedHooks.cs
- patches/tModLoader/Terraria.ModLoader/GlobalItem.cs
- patches/tModLoader/Terraria.ModLoader/ItemLoader.cs
- patches/tModLoader/Terraria.ModLoader/ModItem.cs
- patches/tModLoader/Terraria.ModLoader/ModPlayer.cs
- patches/tModLoader/Terraria.ModLoader/PlayerHooks.cs
- patches/tModLoader/Terraria/Player.cs.patch
Changed `ModItem`, `GlobalItem` and `ModPlayer` `GetManaCost` hooks to `ModifyManaCost`. The new hooks closely resemble the new `ModifyWeaponDamage` hooks, which allow modifying the multipliers that affect the value in the end, rather than the value itself.
The change was done after realizing that the previous hook not only didn't took the mana cost multiplier into account correctly, but also didn't allow to temporarily modify it.
See the modified version of the ExampleMagicMissile item.
> Changed GetManaCost to ModifyManaCost

- installer2/Installer.java
As discussed on discord:
`tModLoaderInstaller.jar` provides wrong permission for `Terraria` and `tModLoaderServer` as follows:
```
---x------  1 kreyren kreyren      133 Jun 14 23:45 Terraria
---x------  1 kreyren kreyren     1151 Jul  1 20:52 tModLoaderServer
```
Which won't open Terraria on Linux due permission issue.
Expecting Read+Write+Executable as:
```
-rwxrwxrwx  1 kreyren kreyren      133 Jun 14 23:45 Terraria
-rwxrwxrwx  1 kreyren kreyren     1151 Jul  1 20:52 tModLoaderServer
```
Reference: https://discordapp.com/channels/103110554649894912/436261997416546305/596861420944097304
---
Requires sanity check since i'm not the best in java..
> Bugfix of permission on linux in installer

- FUNDING.yml
GitHub allows for the displaying of a Sponsor button on public repositories.
The button, when clicked, opens a window containing one or more links to funding platforms, such as Patreon, Ko-fi, Open Collective or [even GitHub itself]!
Those links are specified in the [`FUNDING.yml` file](https://help.github.com/en/articles/displaying-a-sponsor-button-in-your-repository#about-funding-files) in the root of the repository.
After accepting this pull request, the Support button [should be enabled in the repository settings](https://help.github.com/en/articles/displaying-a-sponsor-button-in-your-repository#displaying-a-sponsor-button-in-your-repository).
I couldn't find any other tModLoader funding pages other than [the official Patreon](https://www.patreon.com/tModLoader), so I added that to …
> Add a Sponsor button on GitHub linking to the Patreon

- patches/tModLoader/Terraria.ID/BuffID.cs.patch
- patches/tModLoader/Terraria.ModLoader.IO/PlayerIO.cs
- patches/tModLoader/Terraria.ModLoader/BuffLoader.cs
- patches/tModLoader/Terraria.ModLoader/Mod.cs
- patches/tModLoader/Terraria/Main.cs.patch
- patches/tModLoader/Terraria/MessageBuffer.cs.patch
- patches/tModLoader/Terraria/Mount.cs.patch
- patches/tModLoader/Terraria/NetMessage.cs.patch
- patches/tModLoader/Terraria/Player.cs.patch
`Player.maxBuffs` is a property defining the (de)buff limit within Terraria, it is a constant property, meaning that it is unchangeable and set at compile time.
This PR aims to make the buff limit changeable from a single property rather than hooking **28** (see below) different methods that affect the buff limit.
The way this is accomplished is by
- Changing `Player.maxBuffs` from `const` to `static`
- Modifying all points where `22` (vanilla buff limit) became hard-coded to reference `Player.maxBuffs`
- There could be an optional `maxBuffs` parameter within the Player constructor which defines the limit, defaulting to 22
- Another option could be adding a `maxBuffs` property to `ModLoader.ModPlayer` enabling the same functionality while leaving `Player.maxBuffs` completely vanilla
This …
> WIP feat: Make max (de)buff limit modifiable

- patches/tModLoader/Terraria.ModLoader/NPCLoader.cs
- patches/tModLoader/Terraria/Main.cs.patch
- patches/tModLoader/Terraria/Player.cs.patch
* Changed `NPCLoader.CanChat` so it receives the default CanChat behavior as a parameter.
* Added `NPCLoader.CanChat` call to the NPC smart select code that only gets called if the NPC is a town NPC, to mimic vanilla behavior.
#665
> Fix Smart Select bypassing ModNPC and GlobalNPC CanChat

- patches/tModLoader/Terraria.ModLoader/ItemLoader.cs
- patches/tModLoader/Terraria.ModLoader/NPCLoader.cs
- patches/tModLoader/Terraria.ModLoader/PlayerHooks.cs
- patches/tModLoader/Terraria.ModLoader/ProjectileLoader.cs
This PR stops many bool-returning 'Pre' and 'On' Player, NPC and Projectile hooks from being able to cancel each other out (with their random order), where it makes no sense, to improve mod cross-compatibility. There's zero sense to why a call of a hook like PreAI should get cancelled just because some other call (sorted pretty much randomly) wants to prevent AI from running. PreAI is not AI, and it's not specialized-sounding ShouldCallAI.
Sounds too simple for there to be any.
With how things currently are, mod devs are screwing up each other without knowing, by just using the hooks they're supposed to use.
None? If someone's vile enough to want to stop others' hooks from being called, they can use MonoMod.
Hooks are used the same.
But I can show you what I and others will **no longer** …
> Change behavior of bool-returning PreX and OnX hooks.

- ExampleMod/ExamplePlayer.cs
When the player has a `Charm of Example` or`ExampleCostume` worn, this will make the `blockyAccessory` field in ExamplePlayer true, I have added 2 lines of code that check if this field is true, one disables the default sound([Line 452](https://github.com/KryptonIon/tModLoader/blob/5e0b7d544f145dd20f8c55bb2fe943239e5272ef/ExampleMod/ExamplePlayer.cs#L452)) and the other plays a the frog sound([Line 460](https://github.com/KryptonIon/tModLoader/blob/5e0b7d544f145dd20f8c55bb2fe943239e5272ef/ExampleMod/ExamplePlayer.cs#L460))
N/A
Quoted from the issue this is trying to fix,
> This will show off how to accomplish FrostArmor type hurt sound replacements.
Modders can simply look at ExampleMod instead of asking on Discord.
N/A
#522
`if (blockyAccessory) playSound = false;` In PreHurt
`if …
> FrostArmor type hurt sound replacements.

- patches/tModLoader/Terraria/Projectile.cs.patch
See issue #751 for a detailed breakdown of the vanilla code that these commits edit. A brief description is also included as a comment on the changed code.
The change enforces a minimum value on the "responsiveness" of any yoyo: `1.01`. This prevents the velocity recombination math which governs the yoyo's movement from breaking when the responsiveness value is less than 1. In the vanilla game, the responsiveness value can become less than 1 when a yoyo's effective top speed (boosted by melee speed) is greater than 26. This is possible by using the Terrarian and stacking a ton of melee speed, or by using even faster modded yoyos.
It would also be possible to enforce a minimum value of exactly `1.0`. I decided against this because a yoyo with responsiveness `1.0` snaps instantly to move …
> Fixes #751 (fix for very high speed yoyos)

- ExampleMod/Items/ExampleDashAccessory.cs
Fixes a few typos regarding setting the `ExampleDashPlayer.DashDir` field due to copy/paste laziness.
n/a
The example dash won't function properly without this change.
See previous section.
n/a
n/a
n/a
> Fixed Some Typos in ExampleDashAccessory

- patches/tModLoader/Terraria.ModLoader.Core/AssemblyManager.cs
- patches/tModLoader/Terraria.ModLoader.Core/ModCompile.cs
This change adapts #417 to work with XNA/FNA instead of Mono/Windows. A bit of extra code is required to support noCompile mods because tML needs to include both dlls if they exist, rather than just picking one as is done during compilation.
Updated sample usage:
* In build.txt, dllReferences = CoolLibrary
* In lib folder,
* CoolLibrary.dll (XNA)
* CoolLibrary.FNA.dll
* Compiled {modName}.XNA.dll uses CoolLibrary.dll
* Compiled {modName}.FNA.dll uses CoolLibrary.FNA.dll
Since the purpose of this request is the same as that of #417, please refer to the request description there.
> When compiling and loading mods, check for {Dep}.XNA.dll and {Dep}.FNA.dll

- ExampleMod/Tiles/ExampleCommandSign.cs
- Add a comment containing "ExampleSign" and "ExampleCommandCaller" so it can be searched by either term
- Adjust sign anchors so they're more stable
This PR are subtle changes to the ExampleCommandSign aimed to improve placement stability and make it easier to search for in the GitHub search engine. 
A comment containing "ExampleSign" and "ExampleCommandCaller" has been added so that the ExampleMod can be searched by either term. ExampleCommandSign does not encompass either term and can not be easily searched for without knowing of its existence.
The anchors have been adjusted to be able to place the ExampleSign on trees, make the sign less jumpy to place, and to ensure all tiles are anchored throughout the tiles. 
N/A
With these changes, the ExampleCommandSign example will be a much …
> Stabilize ExampleSign anchors, add search terms

- patches/tModLoader/Terraria.ModLoader.Default/MysteryTile.cs
- patches/tModLoader/Terraria.ModLoader.Default/MysteryTilesWorld.cs
Mousing over a mystery tile will now show the mod and tile name of the unloaded tile.
From #613 
Helpful for knowing what specific mod an unloaded tile was from.
No. It is intended to be a rather simple, basic, and functional. As it stands, it requires no changes to the base game.
Somewhat niche but still, having a way to discern between multiple unloaded tiles that otherwise look completely identical could be useful at times.
None
> Added hover text to MysteryTile

- patches/tModLoader/Terraria.ModLoader.UI/UIModItem.cs
- patches/tModLoader/Terraria.ModLoader.UI/UIMods.cs
- patches/tModLoader/Terraria.ModLoader/ModLoader.cs
From #815 .
When there are a large number of mods installed, using Enable All or Disable All will always cause a lag spike, even if only a few mods would change. This is because it allows it to Enable/Disable a mod which has already been Enabled/Disabled respectively. When it is enabled, it tells it to save the set of enabled mods which it has to do for every mod.
Added a quick check to return when told to enable/disable while already in that state.
Also added a property to pause saving EnabledMods list. Once it is unpaused, if any changes were made, it will automatically save the new list. With this, I implemented it around all cases where multiple mods would be enabled/disabled in a loop (like for mod dependencies and for the enable/disable all buttons).
Not likely without some …
> Fix enable/disable mods lag/freeze with many mods

- patches/tModLoader/Terraria.ModLoader.Core/ModCompile.cs
- patches/tModLoader/Terraria.ModLoader.UI/UIBuildMod.cs
- patches/tModLoader/Terraria.ModLoader.UI/UIErrorMessage.cs
- patches/tModLoader/Terraria.ModLoader/ModLoader.cs
This PR adds a new button that allows the modder to retry building and loading their mod. It only appears if the error is that of a build failure, and it doesn't appear otherwise (e.g due to mod load failure). Useful for saving 1-2 clicks and implements the suggestion in #804 
(This PR also fixes a very small issue with the CompileError message. The bug was that the string was formatted with the error message in place of the number of warnings. I feel like the fix was too small to warrant a separate PR 😛 )
A small quality-of-life addition to make mod dev lives a little easier. It's also helpful in the _extreme_ case a modder's mod sources list takes a long time to repopulate (for whatever odd reason).
Perhaps separate the button into two, where one retries the build and the other retries …
> Add retry build button, fix tiny error in compile failed message

- patches/tModLoader/Terraria/Main.cs.patch
TileLoader.SpecialDraw call was being skipped with faulty if & continue statements in the new code. Reverted the if block to how it was in 1.3.5.2.
> Fixed Mod/GlobalTile.SpecialDraw not working.

- patches/tModLoader/Terraria.ModLoader.Core/LogArchiver.cs
- patches/tModLoader/Terraria.ModLoader/Logging.cs
This pull request changes the way log archiving works, making archived logs go to Logs/Old and not Logs
This should be a change seen in tModLoader because
- It helps declutter the Logs folder
The logs folder seems quite cluttered and adding that folder for old logs seems necessary.
- It will cause less confusion
When others and myself ask users to send their logs, they sometimes get confused and send an archived log zip when they should have sent their client.log.
A design choice I chose not to implement was zipping up the Old folder. I chose not to do this because it could be harder to access archived logs.
Another choice I chose to not implement was moving old archived logs to the Old folder and not just deleting them. I chose not to do this because I thought no one would want to view …
> Better Log Archiving

- patches/tModLoader/Terraria.ModLoader/Logging.cs
OutOfMemory may occur inside FirstChanceException when, for example, trying to allocate enough memory to show the message box.
I added code to unload Main.tile array and call GC.Collect() as early in the method as possible, and also disabled any ways of blocking the handling of the exception.
This is the most practical solution, but not the most good looking.
> Improved stability of OutOfMemory handling

- patches/tModLoader/Terraria/Program.cs.patch
Terraria uses only a single core to pre-JIT its methods during startup. Using multiple cores can speed this up. The difference is quite noticeable on my i7-4800MQ (8 cores) with tML 1.3 or vanilla 1.4. I expect that the time spent loading mods will dwarf the pre-JIT time on most end-user machines, but every little bit helps, especially when you're developing or testing code.
Topics for discussion:
- Is this of interest to tML at all? If all developers are assumed to be using the QuickLaunch startup option to bypass the pre-JIT step entirely, there won't be as much point to having it.
- The number of cores used is at the TPL's discretion. There could be configuration for this.
- Projectile.VanillaAI and (especially) NPC.VanillaAI take much longer to JIT than anything else does. They could …
> Proposal: Use multiple cores to pre-JIT methods

- patches/tModLoader/Terraria.ID/PaintID.cs
Adds a class containing magic numbers associated with paints for tiles and walls, such as:
`public const byte Violet = 11;`
Heavily improves access to paints and their readability.
How I did it before this to sort of "humanize" paints is create an item cache of valid paint items, and then access their paint through a dictionary so it would look like this: 
`byte paint = PaintCache[ItemID.RedPaint];`
```cs
byte paint = PaintID.Red;
WorldGen.paintTile(i, j, paint);
WorldGen.paintWall(i, j, paint);
```
Doesn't seem like something needing a showcase as it's a simple replacement for magic numbers
> Add PaintID

- patches/tModLoader/Terraria.ModLoader.UI/Interface.cs
- patches/tModLoader/Terraria/Program.cs.patch
Improving upon the error messages that are shown by `ModLoader.UI.Interface.MessageBoxShow` to point users towards their client.log file and, depending on the exception, provides a unique tip that may fix it.
(If tModLoader does not recognize the exception, no tip is shown, but it will still point you towards client.log)
It may help alleviate constantly needing to provide users with the same solutions for frequent errors/exceptions by pointing them in the right direction immediately, allowing them to give it a shot at fixing the error themselves (or at least letting them know the importance of your client.log file 😛 ).
Changing error messages, adding/removing exception tips, or just modifying what is shown in general.
These are examples of some of the new error messages (all exceptions …
> Add improved MessageBoxShow error messages

- patches/Terraria/Terraria/Program.cs.patch
- patches/tModLoader/Terraria.Localization.Content/en-US.tModLoader.json
- patches/tModLoader/Terraria.ModLoader.Engine/HiDefGraphicsIssues.cs
- patches/tModLoader/Terraria.ModLoader.Engine/InstallVerifier.cs
- patches/tModLoader/Terraria.ModLoader/Logging.cs
- patches/tModLoader/Terraria/Main.cs.patch
- patches/tModLoader/Terraria/Program.cs.patch
Make `MessageBox` texts localizable, resolves #955
I'm not sure if the logging part should be localizable (which might break some format), so only `MessageBox` related strings were added right now.
> Make MessageBox texts localizable

- ExampleMod/Items/ExampleHook.cs
- patches/tModLoader/Terraria.ModLoader/GlobalProjectile.cs
- patches/tModLoader/Terraria.ModLoader/ModProjectile.cs
- patches/tModLoader/Terraria.ModLoader/ProjectileLoader.cs
- patches/tModLoader/Terraria/Player.cs.patch
Adds a new hook, called `GrappleTargetPoint`, which allows changing the position a grappling hook pulls the player towards.
Also adds the ability to use `ModProjectile.aiType` to use the vanilla implementations of `TrackHook`, `AntiGravityHook`, and `StaticHook`.
Currently it is not possible to create grappling hooks similar to the Anti-Gravity Hook or Static Hook without IL editing or completely overriding the regular grapple code. This would allow it.
Using IL patches or completely overriding the `Player.GrappleMovement` functionality with custom code
See included ExampleMod example
Updated `ExampleHook.cs` to include a sample usage of this feature, which causes ExampleHook to suspend the player 50px away from the hook's position rather than pulling them all the way.
> Grapple target point hook + aiType

- patches/tModLoader/Terraria.ModLoader.UI/UICreateMod.cs
Resolves tModLoader/tModLoader#987
The BasicSword input does not clear properly from the Mod Sources > Create Mod screen
Added a SetText("") reset to the OnActivate() function that matches how we are resetting the other inputs on this screen.
None known. This is a simple change that matches existing patterns.
> Fix issue with BasicSword not clearing during Mod Creation

- patches/tModLoader/Terraria.Localization.Content/en-US.tModLoader.json
- patches/tModLoader/Terraria.ModLoader.UI/UIManagePublished.cs
Changed from when in the manage publish menu without internet to show "Mod Browser Offline (Unknown)" instead of "Mod Browser OFFLINE ()"
Having offline all in caps isn't pleasant, in my opinion, and doesn't look nice with the other normal capitalized text. Brackets without anything in them doesn't seem correct, either.
This capitalization change may affect other languages.
I don't feel like this is a bug or a feature so I hope it's fine if I write without a template
My first PR since 0.11.7.X so I hope I did well 😅 ..also my first PR using a proper git service
> Changed Localization Caps & UIManagePublished Error Text

- patches/tModLoader/Terraria.ModLoader/ModContent.cs
Tile Entities would not unload properly when mods are unloaded - this causes mods that add ModTileEntities to display the "not fully unloaded" warning (and the TEs would still nastily live on in memory, causing issues for some mods). Issue is documented in #762.
Add a `TileEntity.Clear();` in `ModContent.CleanupModReferences`
maybe?
> Fix ModTileEntities not unloading properly

- patches/tModLoader/Terraria/Item.cs.patch
A new constructor for Item that lets you supply a type.
It prevents unnecessary extra code, since with this it is now possible to do:
`Item item = new Item(ItemID.Whatever);`
instead of:
`Item item = new Item();`
`item.SetDefaults(ItemID.Whatever);`
> New item constructor that lets you specify a type.

- ExampleMod/Content/Items/Accessories/WaspNest.cs
- ExampleMod/Content/Items/Tools/ExampleHook.cs
- patches/tModLoader/Terraria/Main.cs.patch
- patches/tModLoader/Terraria/ModLoader/AutoloadAttribute.cs
- patches/tModLoader/Terraria/ModLoader/Core/ModOrganizer.cs
- patches/tModLoader/Terraria/ModLoader/GlobalBuff.cs
- patches/tModLoader/Terraria/ModLoader/GlobalItem.cs
- patches/tModLoader/Terraria/ModLoader/GlobalNPC.cs
- patches/tModLoader/Terraria/ModLoader/GlobalProjectile.cs
- patches/tModLoader/Terraria/ModLoader/GlobalRecipe.cs
- patches/tModLoader/Terraria/ModLoader/GlobalTile.cs
- patches/tModLoader/Terraria/ModLoader/GlobalWall.cs
- patches/tModLoader/Terraria/ModLoader/Mod.Internals.cs
- patches/tModLoader/Terraria/ModLoader/ModBackgroundStyle.cs
- patches/tModLoader/Terraria/ModLoader/ModBuff.cs
- patches/tModLoader/Terraria/ModLoader/ModCommand.cs
- patches/tModLoader/Terraria/ModLoader/ModContent.cs
- patches/tModLoader/Terraria/ModLoader/ModDust.cs
- patches/tModLoader/Terraria/ModLoader/ModItem.cs
- patches/tModLoader/Terraria/ModLoader/ModMountData.cs
- patches/tModLoader/Terraria/ModLoader/ModNPC.cs
- patches/tModLoader/Terraria/ModLoader/ModPlayer.cs
- patches/tModLoader/Terraria/ModLoader/ModPrefix.cs
- patches/tModLoader/Terraria/ModLoader/ModProjectile.cs
- patches/tModLoader/Terraria/ModLoader/ModTile.cs
- patches/tModLoader/Terraria/ModLoader/ModTileEntity.cs
- patches/tModLoader/Terraria/ModLoader/ModType.cs
- patches/tModLoader/Terraria/ModLoader/ModWall.cs
- patches/tModLoader/Terraria/ModLoader/ModWaterStyle.cs
- patches/tModLoader/Terraria/ModLoader/ModWorld.cs
Changes to my last autoloading system:
- `AutoloadAttribute` now allows you to specify a `ModSide` which will control when a type can be autoloaded (client side, server side, or both).
- The base tML ModTypes now expose the implemented `Load(Mod)` method. This unifies the loading and removes the `Load()` and `AddInstance()` methods. Anyone wanting to overload `Load(Mod)` will need to call `base.Load(mod)` to ensure their ModType is loaded.
Remaining things todo/discuss before merging:
> Better Autoloading 2

- patches/tModLoader/Terraria/ModLoader/ModLoader.cs
- patches/tModLoader/Terraria/ModLoader/UI/DownloadManager/DownloadFile.cs
- patches/tModLoader/Terraria/ModLoader/UI/DownloadManager/UIDownloadProgress.cs
- patches/tModLoader/Terraria/ModLoader/UI/UILoadMods.cs
- patches/tModLoader/Terraria/ModLoader/UI/UIMemoryBar.cs
- patches/tModLoader/Terraria/ModLoader/UI/UIModSourceItem.cs
- patches/tModLoader/Terraria/ModLoader/UI/UIProgress.cs
Shows the total download/upload progress in KB or MB based on size, as well as the average speed in the appropriate unit per second. Additionally, moved some code from UILoadMods to UIProgress so that the small text below the bar exists on all UIProgress instances.
Because of https://github.com/tModLoader/tModLoader/issues/775 (can now be marked as complete).
No.
https://cdn.discordapp.com/attachments/445276626352209920/738089021133160578/unknown.png
https://cdn.discordapp.com/attachments/445276626352209920/738094672039248023/unknown.png
> Added download/upload telemetry to mod downloads and uploads

- patches/tModLoader/Terraria/ModLoader/UI/UIModSourceItem.cs
Does what it says. Solves #1050, with very little code :^)
To be honest, I'm not sure. This implementation definitely works but I dunno if it fits your guys' idea of good practice. In the future, maybe a new translation key that reads "Reload Before Publishing" or just "Reload" (which would fit a lot better actually) that can be used instead just reusing the "Reload Mods" one might be nice, but I think any modder who reads it should probably be able to figure it out based on context anyway.
> Enforce reload before publishing

- patches/tModLoader/Terraria/GameContent/Liquid/LiquidRenderer.cs.patch
A missing water asset causes a `NullReferenceException` resulting in a CTD. Specifically, `Water_12`.
By changing the # of water textures to load from 12 to 13.
On 1.4.0.5; I can confirm there are 13 water files, so I'm not sure if this was a mistake, or if a version of 1.4 only has 12 assets.
The draw code for water could be patched to fail safely when missing a water asset.
> Fix for water CTD

- patches/tModLoader/Terraria/DataStructures/PlayerDrawLayers.cs.patch
Custom Back Accessories are not visible on the player.
Removed the check which would only show Vanilla back items.
Also changed shield's code for consistency with the rest of the limit removals.
> Back Accessory BugFix

- patches/tModLoader/Terraria/MessageBuffer.cs.patch
Fixes #1087
`ModWorld.NetReceive` is ran before `ModWorld.Initialize`
1.3 Port of the fix used for 1.4 from #1090
See #1090
> 1.3 Potential Fix #1087

- ExampleMod/Items/ExampleFishingRod.cs
- ExampleMod/Projectiles/ExampleBobber.cs
Adds an example item to ExampleMod called Example Fishing Rod.
It gives examples of how to fish in lava, fire multiple lines, and randomize line colors.
This is an example item for Example Mod which modders can reference to see how to make a fishing rod, specifically the draw code in the bobber file in order for the line to draw properly.
Provides an example of a fishing rod with various attributes
Provides an example of a bobber with a properly drawn line and can have randomized colors
**N/A**
**N/A**
This item is in Example Mod. It is an example item, and it is its own sample usage.
> Added example fishing rod

- patches/tModLoader/Terraria.ModLoader/GlobalTile.cs
Not necessarily a bug, but made KillTile easier to read
change from "fail determines whether the tile is mined" to that *and* "fail determines whether the tile is mined. Being true means not mined"
Nope.
> Gave KillTile an easier to understand summary

- patches/tModLoader/Terraria/Item.TML.cs
- patches/tModLoader/Terraria/ModLoader/DamageClass.cs
- patches/tModLoader/Terraria/ModLoader/DamageClassLoader.cs
- patches/tModLoader/Terraria/ModLoader/VanillaDamageClasses.cs
- patches/tModLoader/Terraria/Projectile.TML.cs
- patches/tModLoader/Terraria/Projectile.cs.patch
you may now use DamageClass.Throwing to define a throwing item/projectile, this is for modded convenience since everyone and their dog does a throwing class
you may now assign a DamageClass to projectiles through projectile.DamageType
also added an attempt at a fix for a problem where all DamageClasses are boosted by all stat bonuses for no good reason, and by that I mean I just made it so their indexes are actually set ever, it doesn't work 100% but it might help. see the issue I made on that for more info
> DamageClass additions and fixes.

- patches/tModLoader/Terraria/NetMessage.cs.patch
Modded projectiles which both use the vanilla UUID system `ProjectileID.Sets.NeedsUUID[i] = true` and TML's provided "Extra AI" (`ModProjectile.SendExtraAI` and `ModProjectile.ReceiveExtraAI`) run into misaligned netcode due to a typo in `NetMessage.cs`.
Specifically, when writing a `SyncProjectile` packet, TML sends the modded "Extra AI" before the vanilla code which sends UUID. But when reading a `SyncProjectile` packet, TML reads the "Extra AI" *after* vanilla code reads the UUID.
I reordered `NetMessage.SendData case 27:` instructions so that the vanilla UUID is sent before the "Extra AI". This was the recommendation by @Chicken-Bones (mod data should always be at the end if feasible).
Instead of modifying the packet write, the packet read could be modified by making …
> Fix projectiles with both UUID and ExtraAI having misaligned netcode read/write

- patches/tModLoader/Terraria/Gore.TML.cs
- patches/tModLoader/Terraria/Gore.cs.patch
- patches/tModLoader/Terraria/ID/GoreID.cs.patch
- patches/tModLoader/Terraria/Main.cs.patch
- patches/tModLoader/Terraria/ModLoader/GoreLoader.cs
- patches/tModLoader/Terraria/ModLoader/Mod.Internals.cs
- patches/tModLoader/Terraria/ModLoader/Mod.cs
- patches/tModLoader/Terraria/ModLoader/ModContent.cs
- patches/tModLoader/Terraria/ModLoader/ModGore.cs
This PR does the following:
- Fixes ModGore, as it just hasn't been working for some reason I don't even know.
- Splits ModGore into GoreLoader, improve some code quality in general.
- Turns ModGore into a ModTexturedType. Reduced the amount of hardcode in autoloading.
- Changes how Texture-only mod gores load. Now, for every such gore, a dummy ModGore is registered with ModName/TextureName FullName. This means that gores can now be gotten using Mod/ModContent.Find/TryFind, which do not use texture paths.
- Mod.AddGore is replaced with GoreLoader.AddGoreFromTexture, which does what you would think, i.e. what I described above.
- Removes by-texture-path GetGoreSlot methods, for less hardcode and way less confusion. Content devs seem to support the switch from texture paths to …
> [1.4] Fixed and reworked ModGore

- patches/tModLoader/Terraria/ModLoader/Default/Patreon/Orian.cs
- patches/tModLoader/Terraria/ModLoader/EquipLoader.cs
- patches/tModLoader/Terraria/ModLoader/EquipTexture.cs
- patches/tModLoader/Terraria/ModLoader/GlobalItem.cs
- patches/tModLoader/Terraria/ModLoader/ItemLoader.cs
- patches/tModLoader/Terraria/ModLoader/ModItem.cs
- patches/tModLoader/Terraria/ModLoader/ModPlayer.cs
- patches/tModLoader/Terraria/ModLoader/PlayerHooks.cs
- patches/tModLoader/Terraria/Player.cs.patch
- VanillaUpdateAccessory no longer erroneously uses player.whoAmI as an input.
- VanillaUpdateAccessory and ApplyEquipsVanity now account for extra acc slots properly, preventing the game from hanging upon having one.
- extraAccessorySlots now properly updates itself in ResetEffects.
- skyStoneEffects (Sun/Moon Stone statsheet) is no longer applied for every slot starting with the one where the stone in question is equipped.
> Fixed multiple accessory-related issues.

- patches/tModLoader/Terraria/Main.cs.patch
- patches/tModLoader/Terraria/ModLoader/ModWorld.cs
- patches/tModLoader/Terraria/ModLoader/WorldHooks.cs
it's about time, as they say
edit the `timeRate` parameter to modify the speed at which time progresses, edit the `tileUpdateRate` parameter to modify the speed at which tiles in the world update
can be useful for items or events which are meant to speed up or slow down time
> Added ModWorld.ModifyTimeRate.

- patches/tModLoader/Terraria/ModLoader/IO/TagSerializer.cs
TagSerializer implements ILoadable.
It simply grants peace of mind to the average modder. I think that whenever possible with these kind of OOP objects that only get instantiated once, at load time, they should always be automatically handled. Unless they have to explicitly defined, which TagSerializers usually don't have to be, the API should just do it for the user.
> made TagSerializer implement ILoadable

- ExampleMod/Content/Items/Accessories/ExampleShield.cs
The dash accessory was implemented by enumerating the player's accessory slots. This approach is contrary to the vanilla and tML design where accessories enable capabilities on the player, and prevents all accessory related hooks or custom slots from working with it.
The new design also puts the movement code in the `PreUpdateMovement` hook, consistent with other movement affecting code.
Overall operation should be easier to understand. Posting here for feedback/thoughts.
> Actually fix ExampleShield (best practice)

- README.md
tModLoader 404s on discord.me so I replaced it with the normal Discord invite link.
Discord also now owns the discord.com domain so I changed discordapp.com to discord.com as well.
Fixes #1239
> Fix #1239 (Update Discord links in README.md)

- patches/tModLoader/Terraria/ModLoader/NPCLoader.cs
There are errors when compiling tModLoader on the latest commit of `1.4_mergedtesting`, this is because the `SetBestiary` hook was duplicated.
The hook was duplicated in commit https://github.com/tModLoader/tModLoader/commit/a3a1e353820e0f78dde633ba8cbfb3bd4a02fc28
Remove the duplicated hook
no
Image of duplicate hook:
> Fix duplicate hook in NPCLoader.cs

- patches/tModLoader/Terraria/MessageBuffer.cs.patch
The client crashes when opening a chest in multiplayer.
`Main.chest[num261]` was null which seemed like a typo from f33571a. I changed it to 260 then opened a chest successfully.
This project is still kind of magic to me, so I don't know.
> [1.4] Fix crash when opening chests in mutliplayer

- patches/tModLoader/Terraria/GameContent/Biomes/DeadMansChestBiome.cs.patch
There is a rare crash during world generation due to an out-of-bounds array index exception. 
1. Build ExampleMod for 1.4 (you might need to change `new Before(...` to `new BeforeParent(...` in ExamplePlayerDrawLayer.cs)
2. Enable ExampleMod (this will bump the length of `Main.tileSolid` and other tile arrays to 640)
3. Create a `Medium` sized `Journey` world with `Crimson` and seed `678930300`
4. The game should crash in `Micro Biomes` world generation phase
Instead of 624 fixed sized array, borrow the correct size from `Main.tileSolid`. There doesn't appear to be a constant for the tile count so this seemed like the most straight forward way. This fix simply makes `PlaceBoulderTrapSpot` agnostic to what the maximum number of tile types in the game is.
If there is an up-to-date constant …
> [1.4] Fix crash with world generation (PlaceBoulderTrapSpot)

- ExampleMod/Common/ExamplePlayerDrawLayer.cs
Fix ExampleMod for 1.4. From my brief testing it seems like the only thing that needed to be done is changing `Before` -> `BeforeParent` in ExamplePlayerDrawLayer.cs.
> [1.4] Fix ExampleMod

- patches/tModLoader/Terraria/ModLoader/UI/UIMemoryBar.cs
Fixes crash when hovering over memory tooltip on the "Mods" page as described in the issue https://github.com/tModLoader/tModLoader/issues/1244
Crash seems to be caused by editing render hierarchy during drawing, which raises an exception somewhere down the line. Fix simply removes the part of code that appends `_hoverPanel` into `UIMemoryBar`'s parent element's render tree. This also means that the relative offsetting to `Parent.GetDimensions()` can be removed since `_hoverPanel` is now rendered relative to 0 0. I also changed some of the magic offsets to preserve the original look of the tooltip.
I'm pretty new to this project so I can't say that this is the best or correct way to fix the issue
> [1.4] Fix crash with memory statistics tooltip

- patches/tModLoader/Terraria/Main.cs.patch
`ModLoader` is namespace, no methods
so change `ModLoader` to `ModLoader.ModLoader`, now compiler happy and you can use methods
> [1.4] Small issue preventing compilation

- patches/tModLoader/Terraria/Main.cs.patch
`GlobalNPC.PostDraw` is only called when `PreDraw` returns false
By adding a call to `NPCLoader.PostDraw` inside the `DrawNPCDirect` method. The call was added in the same position as it was in 1.3
no
Also, can whoever accepts this merge this PR and #1250 to `1.4_mergedtesting` so that I can finish making `ModdersToolkit` work for that branch.
> Add call to "GlobalNPC.PostDraw"

- patches/tModLoader/Terraria/Netplay.cs.patch
Resolves longstanding issue of multiplayer frame drops.
Patch 1.3 per the following change: https://github.com/tModLoader/tModLoader/pull/1272/commits/31713772a7d5c2c8534199581cfc4dd994c985f5
As part of: https://github.com/tModLoader/tModLoader/pull/1272
*My opinion* is we should patch this on 1.3 as well, while 1.4 is still being developed.
> [Changes Requested][1.3] Resolve multiplayer frame drops in 1.3 version, matching PR 1272 of 1.4

- patches/tModLoader/Terraria/Localization/Content/en-US/tModLoader.json
- patches/tModLoader/Terraria/ModLoader/UI/UIModItem.cs
This feature allows the user to quickly delete disabled mods without having to go into the More Info menu.
Because it's currently hard to quickly delete mods inside tModLoader.
Yes, issue #1271 has a similar concept design.
(Pressing L/R Shift skips the dialog box)
https://user-images.githubusercontent.com/30240961/106326907-2d8f6500-6275-11eb-9a59-02f711b5ccf7.mp4
Notes: 
- The trash icon might need to be updated, I simply made use of an already existing asset.
- I couldn't quite manage to center the wrapped text in the dialog box, I'd love some feedback (and help) on it.
> [1.4] Quick Mod Delete

- ExampleMod/Common/GlobalBossBars/ExampleGlobalBossBar.cs
- patches/tModLoader/Terraria/GameContent/UI/BigProgressBar/BigProgressBarHelper.cs.patch
- patches/tModLoader/Terraria/ModLoader/BossBarLoader.cs
- patches/tModLoader/Terraria/ModLoader/GlobalBossBar.cs
- patches/tModLoader/Terraria/ModLoader/ModBossBar.cs
Follow-up on the PRs #1316 and #1288, the latter one adding a skipped parameter on the `1.4` branch, which this PR removes. Reason: Lack of definitive use cases
> [1.4] Remove skipped parameter from BossBarLoader.PostDraw

- patches/tModLoader/Terraria/Item.cs.patch
- patches/tModLoader/Terraria/ModLoader/GlobalItem.cs
- patches/tModLoader/Terraria/ModLoader/ItemLoader.cs
- patches/tModLoader/Terraria/ModLoader/ModItem.cs
Implementation of improvements suggested in #1040. CanBurnInLava hook can now be used to either force an item to burn in lava regardless of any conditions or the opposite. The order of precedence is set such as suggested by @Chicken-Bones in #1040.
This rework allows for a better control of whether the item will burn or not by completely ignoring vanilla rules if needed (the only exception is the Guide Voodoo Doll, as i'm not sure what could be the use case here that don't just break the game). As mentioned in #1040, before it was impossible to make the item not burn by using this hook.
While i think the current order of precedence makes sense, other orders are possible. I think there is no single right anwser here, so we should just stick to whatever works in most cases, which seems to …
> [1.4] CanBurnInLava hook rework (implements #1040)

- patches/tModLoader/Terraria/Item.cs.patch
- patches/tModLoader/Terraria/ModLoader/GlobalItem.cs
- patches/tModLoader/Terraria/ModLoader/ItemLoader.cs
- patches/tModLoader/Terraria/ModLoader/ModItem.cs
This PR adds a hook for ModItem which returns a boolean which allows the modder to allow items to stack in the inventory but not in the world.
There is an issue for this PR: #1106 
Because it will allow mods to create unique in world item interactions based on certain criteria. (See issue)
See issue
```C#
using Terraria.ModLoader;
public class ExampleItem : ModItem
{
...
public override bool CanStackInWorld(Item item2) {
return false; //Prevents the item from stacking in the world but still allows it to stack in the inventory 
}
}
```
None
> Added a hook to prevent items from stacking in the world

- patches/tModLoader/Terraria/Main.cs.patch
- patches/tModLoader/Terraria/ModLoader/IO/WorldIO.cs
- patches/tModLoader/Terraria/NetMessage.cs.patch
- patches/tModLoader/Terraria/Netplay.cs.patch
- patches/tModLoader/Terraria/WorldGen.cs.patch
Currently the location of TileIO.PostExitWorldCleanup is run during in world save and continue, despite being intended for during exiting a world after save has occurred.
This PR moves it to occur after WorldFile.SaveWorld() during the cases where the world is closing.
I couldn't find a singular spot to 'cleanup' so to speak on world exit.
> Fix tile IO post cleanup on exit call

- patches/tModLoader/Terraria/ModLoader/IO/TileIO_Basic.cs
Bring back pathing functionality from https://github.com/tModLoader/tModLoader/tree/2aeb37630e1fc196d459b09814d1b39ebbffd8b4/patches/tModLoader/Terraria/ModLoader/IO
Fixes ModContent.Find to correctly path based on entry.unloadedType.Length, as legacy worlds will have this as an empty string on first load so they need to use the entry.DefaultUnloadedType.
> Fix Tile IO legacy unloaded

- patches/tModLoader/Terraria/ModLoader/MenuLoader.cs
This bug occurs when a there is a non-vanilla ModMenu active and it is unloaded. This can cause AssetDisposedException's because it attempts to draw the unloaded textures (caused by unloading occurring on a different thread).
Setting the ModMenu to MenutML at the beginning of the unload process.
Something like https://github.com/Mirsario/Terraria-BetterRussian/blob/master/BetterRussianMod.cs, which uses a TaskCompletionSource to await the unloading of the menu assets.
> Fixed a crash with ModMenu during mod building

- patches/tModLoader/Terraria/ModLoader/Default/UnloadedChest.cs
- patches/tModLoader/Terraria/ModLoader/Default/UnloadedDresser.cs
Mining unloaded Chests, Dressers will crash the game due to a stack overflow.
Setting them so they have the correct style templates to match their corresponding set fixes the crash.
> FixStylesOfUnloadedChest and Dresser

- patches/tModLoader/Terraria/ModLoader/Default/UnloadedTile.cs
- patches/tModLoader/Terraria/ModLoader/SoundLoader.cs
1) #1436  
2) Multiplayer hover over unloaded tile bug.
1) Change vanilla count in SoundLoader to be vanilla count, not one more than
2) Re-add the null check against the unloadedEntriesLookup
1) Will become unneeded once SoundFix is merged, but for now patch
2) Straightforward bug fix.
> Fix SoundLoader vanilla count return & fix unloaded tile MP bug

- patches/tModLoader/Terraria/Projectile.cs.patch
In 1.3 tModLoader added a local variable called `knockback`, which was a copy of the projectile's `knockBack` field, to the projectile NPC damage loop, so it could be passed to the various `ModifyHitNPC` methods without chaging the base knockback of the projectile. However, in 1.4 there's now a local variable `num7` that already fulfills the same function, which seems to have been overlooked.
I removed the `knockback` variable, then replaced all instances of `knockback` inside the NPC damage loop with `num7`. 
In the process i realized that vanilla doesn't actually sync it's own modifications to knockback properly, still syncing the `knockBack` field instead.
> [1.4] Projectile knockback fix

- ExampleMod/Common/GlobalItems/ShortswordGlobalItem.cs
- ExampleMod/Content/Items/Weapons/ExampleShotgun.cs
- ExampleMod/Content/Projectiles/Minions/ExampleSimpleMinion.cs
* Changed missed instances of `knockBack` to `knockback`.
* Fixed ExampleShotgun not randomnizing its projectile spread.
> [1.4] Shoot Rework fix

- setup/Properties/Settings.Designer.cs
- setup/Properties/Settings.settings
- setup/Setup/Program.cs
- setup/app.config
The new tML build location should be a separate folder from the steam install. We've decided to set tModLoaderDev as the default.
This PR forces everyone to move to the new folder from this commit on, unless they manually override it again.
> Re-default tML steam dir to tModLoaderDev by renaming setup setting

- ExampleMod/Content/Biomes/ExampleSurfaceBackgroundStyle.cs
- ExampleMod/Content/Biomes/ExampleUndergroundBackgroundStyle.cs
- patches/tModLoader/Terraria/ModLoader/BackgroundLoaders.cs
...Loader.GetBackgroundSlot() does not auto-add the Mod.Name as compared to original Mod.GetBackgroundSlot().
Logging known issue via silently caught error from: "Main.bgAlphaFarBackLayer is resized after surfaceBackgroundStyles is added to in AutoLoad" in Loader.DrawFarTexture(). 
Add ExampleMod\ to all ExampleMod calls;
Toss a quick Count != Array.Length to catch the condition.  
Former no;
Latter maybe? No obvious solution as it appears to be a race condition during mod loading, so moving it from logging silent to internal TODO instead of non-useful error in logs.
> Fix errors tossed from ExampleMod, put a temp fix for DrawFarTexture

- patches/tModLoader/Terraria/ModLoader/TileLoader.cs
#1348 
I added a check against TileIO.Tiles.UnloadedTypes in the CanGrowModCactus hook.
There are several, but this should be the least maintenance option.
Creating a new unloaded type could also be done, but takes more lines and seems unnecessary.
Could also check specific types, but than you have to grab those type values which again seems unnecessary
Could also add the tile to the cacti dictionary, but that creates can complicate things if later adding another unloaded type.
> Fix #1348 

- patches/tModLoader/Terraria/Social/Steam/WorkshopHelper.cs.patch
- Modify Get...SubscribedPaths to handle both tModLoader and Terraria.
- Disable the Workshop publishing code at the next to last step, where modifications will take place later for tModLoader support
Enables use of subscribed vanilla Workshop content.
SteamUGC does not support getting workshop items belonging to other apps unless it originated within that app, so no steam based alternative. The current design is going to also be easier from a GoG perspective later when looking at mod workshop.
> Steam Workshop1: Create readonly connection to vanilla workshop content

- patches/tModLoader/Terraria/Player.cs.patch
- patches/tModLoader/Terraria/Projectile.cs.patch
Makes some private methods from the `Player` and `Projectile` classes public. These methods are very useful, if not entirely required, for implementing content similar to vanilla. The methods in question are:
* **Player**:
* **bool IsTargetTileInItemRange(Item sItem)**: Returns whether the target tile (the one at `Player.tileTargetX`, `Player.tileTargetY`) is within the item's range, taking into account the player's `tileRangeX` and `tileRangeY`, which could have been modified by equipment or buffs, and the item's `tileBoost`. Useful when implementing items that do something to the target tile on use, while taking into account the item's range.
* **int SpawnMinionOnCursor(IProjectileSource projectileSource, int ownerIndex, int minionProjectileId, int originalDamageNotScaledByMinionDamage, …
> [1.4] Make some Player and Projectile methods public

- patches/tModLoader/Terraria/ModLoader/PrefixLoader.cs
Change of PrefixLoader.Roll from internal to public to allow accurate recreation of base tml features without reflection if item.Prefix(-2) is in some way unusable for the situation
> Made PrefixLoader.Roll public

- patches/tModLoader/Terraria/Localization/Content/en-US/tModLoader.json
- patches/tModLoader/Terraria/ModLoader/Engine/InstallVerifier.cs
- patches/tModLoader/Terraria/ModLoader/UI/Interface.cs
- patches/tModLoader/Terraria/Social/SocialAPI.cs.patch
In preparation for moving from Indev to Alpha, this PR addresses a handful of small ToDos.
1) Disables Mod Browser button - Mod Browser as is, is 1.3. Steam Workshop PRs will restore this overtime. As well, its terribly slow due to #1328 
2) Cleanups InstallVerifier check to not require deleting steamapp_id.txt. This file is needed for GoG's steam workshop; also was unnecessary extra install step when better programming exists.
3) Adds a betaWelcomeMessage to clearly denote this is the beta version. **Only appears every run for release builds**
> AlphaPrep: Disable ModBrowser, cleanup InstallVerifier check, add betaWelcomeMessage

- patches/tModLoader/Terraria/NPC.cs.patch
There's a type check in `VanillaHitEffect` that erroneously checks for 667 and above, causing the Golden Slime's fake coin hit effect to be present on all modded NPCs. This simple PR fixes this.
> Fix Golden Slime hit effect on all modded NPCs

- patches/tModLoader/Terraria/Main.cs.patch
Journey mode duplication menu does not respond to mouse scroll (fixes #1475).
I moved the `CreativeMenu.Update` call above where `PlayerInput.ScrollWheelDeltaForUI` is set to 0.
None that I am aware of.
> Fixed duplication menu scrolling

- patches/tModLoader/Terraria/GameContent/UI/Elements/UICharacterListItem.cs.patch
Bug description is found in #1489. 
The bug is caused by the UIText object being positioned over the `Rename` button causing the OnMouseOver event to constantly fire causing the flickering text.
Fixed this by assigning the UITexts left position to use the `num` variable just like in `UIWorldListItem.cs`. This causes the UIText button to be positioned off the of the button preventing the flicker.
Initially, I was going to use the position of the `Rename` button to determine the placement of the `_ButtonLabel` however after cross comparing code to `UIWorldListItem.cs` it seems using the already existent `num` variable that is used is most likely the best practice.
This is my first pull request and I'm unsure if the patch is correct. I applied the patch using the tool and all seemed to be …
> [1.4] Fix rename character label flickering

- patches/tModLoader/Terraria/IngameOptions.cs.patch
`ModSystem.PreSaveAndQuit()` was not being called at all.
Added it to the list of actions called when left-clicking `Save & Exit` from the Ingame Options menu.
There most definitely are, just chose the most accessible way.
> Implemented forgotten ModSystem.PreSaveAndQuit

- patches/tModLoader/ReLogic/Content/AssetRepository.cs.patch
- patches/tModLoader/Terraria/ModLoader/Assets/TModContentSource.cs
- patches/tModLoader/Terraria/ModLoader/Core/MemoryTracking.cs
- patches/tModLoader/Terraria/ModLoader/Mod.Internals.cs
- patches/tModLoader/Terraria/ModLoader/ModContent.cs
- patches/tModLoader/Terraria/ModLoader/ModLoader.cs
The dedicated server was unable to load ModLoader Mod and other mods after changes made on the Asset Loading PR.
This PR adds the necessary null checks to be able to allow for mod loading so that dedicated servers at least can reach their Main Menu.
1) Add null checks in Asset Repository to divert loading of client assets to not happen & not deadlock
2) Add null & main.dedServ checks elsewhere as was required.
> Fix Mod Loading on Dedicated Servers with conditionals

- patches/tModLoader/Terraria/ModLoader/Core/ModCompile.cs
- patches/tModLoader/Terraria/ModLoader/Core/ModOrganizer.cs
- patches/tModLoader/Terraria/Program.cs.patch
- patches/tModLoader/Terraria/Social/Steam/WorkshopHelper.TML.cs
- patches/tModLoader/Terraria/Social/Steam/WorkshopHelper.cs.patch
Mod Building via CLI w/out Steam logged in failed due to attempting to use Steam API.
Server launched as Steam-less by a steam user should have an attempt to find mods installed by Steam in the default location.
Reworked SteamUser to start false, and moved Main.DedServ to be set prior to CLI build.
> Fix ModBuild & improve Mod Finding

- patches/tModLoader/Terraria/ModLoader/UI/UIErrorMessage.cs
#1591
Swapped Process.Start items for their Utils counterparts.
Swapped Environment.Exit() for Mono.Game.Exit() per https://github.com/mono/mono/issues/17317
> Fix Bugs in UI Error Message

- patches/tModLoader/ReLogic/Content/Sources/ContentSource.cs
HasAsset() currently always return false due to the following:
I've taken the less exhaustive approach of just using String.Replace() on the lookup string to convert tML standard forward slash into back slash as needed.
Yes, could also rework AssetExtensions dictionary to be based on forward slash; however elected not to given that the entirety of vanilla assets is standardized to back slash, which likely would take quite a bit more effort to swap over relative to a single String.Replace().
> Patch HasAsset Dictionairy issues

- patches/tModLoader/Terraria/ModLoader/InfoDisplayLoader.cs
An incredibly small PR which does as the title explains. Vanilla info displays should now be listed in the same order as that in which they are listed in vanilla.
> [1.4] Fixed vanilla info displays being listed in the wrong order

- patches/tModLoader/Terraria/ModLoader/GlobalRecipe.cs
- patches/tModLoader/Terraria/ModLoader/RecipeLoader.cs
- patches/tModLoader/Terraria/Recipe.TML.cs
- patches/tModLoader/Terraria/Recipe.cs.patch
Added an index to vanilla recipes and made Recipe.ConsumeItemHooks getter public
Current design require a trick to use ConsumeItemHooks by adding instructions to it or with reflection.
The recipe index is only assigned to the modded recipes while it could be used in some mods, and make the debugging easier.
> Minor changes in Recipe

- patches/tModLoader/Terraria/GameContent/UI/States/UIWorldLoad.cs.patch
- patches/tModLoader/Terraria/ModLoader/Logging.cs
- patches/tModLoader/Terraria/Social/Steam/WorkshopHelper.TML.cs
- patches/tModLoader/Terraria/Social/Steam/WorkshopHelper.cs.patch
- solutions/ReleaseExtras/RuntimeFiles/InstallNetFramework.sh
export COMPlus_DefaultStackSize=4000000 so that the default secondary thread MacOS stack limit of 512kb becomes 4MB and add logging for it being received (untested if it fixes Mac stack size issues)
update Workshop Publisher to error on missing icon/content folder prior to upload instead of during
add logging worldgen stage to log file for easier debugging
update SteamGameServer.Init to actually use its bool return and path better.
update the logging around launch parameters so that if none are used, it doesn't show up in the log 
update the Mac library look change to also include creating the symlink so as to avoid the SegFault issues seen on Linux re-occuring.
> Random Assortment of Patches from MacOS testing

- patches/tModLoader/Terraria/ModLoader/Engine/InstallVerifier.cs
- patches/tModLoader/Terraria/Social/Steam/WorkshopHelper.TML.cs
GoG exe hashes look to be outdated compared to 1.3 master branch.
Doesn't look like updated since 1.4.2.1.
Also update the SteamDownload() to work the same as GoG due to issues found on Linux with relying on the callback.
> Fix GoG hashes and Linux Steam Download

- patches/tModLoader/Terraria/GameContent/UI/States/AWorkshopPublishInfoState.cs.patch
- patches/tModLoader/Terraria/ModLoader/UI/ModBrowser/UIModDownloadItem.cs
- patches/tModLoader/Terraria/Social/Steam/WorkshopHelper.TML.cs
- patches/tModLoader/Terraria/Social/Steam/WorkshopHelper.cs.patch
Vanilla workshop supports images up to 512x512 and have an annoying bug where the workshop visibility defaults to private is the upload is an update.
The correct info could only be shown to mods being in the first page, as only the info of the first page could be shown.
To not break the vanilla workshop, I made so that mod icons would always be resized to 80x80 in the mod browser.
The workshop visibility now works as intended, I guess it will also fix the bug on vanilla upload as the base code is the same, though any mod published before this fix is implemented will need another update before working properly (as the publicity data is missing from the header).
For the info, I added the page shift to fetch the correct info.
For the mod icon, upload could be limited at 80x80, but I don't …
> Workshop fixes

- patches/tModLoader/Terraria/GameContent/ItemDropRules/CommonDrop.cs.patch
- patches/tModLoader/Terraria/GameContent/ItemDropRules/DropOneByOne.cs.patch
- patches/tModLoader/Terraria/GameContent/ItemDropRules/ItemDropDatabase.cs.patch
To help people to debug the drop rates, with this PR, all the vanilla drop rules will throw an exception if the minimum amount of something is below the maximum.
This design prevents people from changing the DropOneByOne.parameters during the game, but I believe that if someone is techy enough to want it, they will have a better design by creating a custom class anyway
I also chose to prevent the bonus per chunk per player from reducing the spread to avoid some unexpected bugs with an high number of players
> New exceptions on invalid drop rule

- patches/tModLoader/Terraria/Projectile.cs.patch
technically a holdover fix until I properly set up a system for this but until then have a 2-second fix
> [1.4] Quick fix to minion shots being able to critically strike

- patches/tModLoader/Terraria/Social/Steam/WorkshopHelper.TML.cs
- patches/tModLoader/Terraria/Social/Steam/WorkshopHelper.cs.patch
- patches/tModLoader/Terraria/Social/Steam/WorkshopSocialModule.TML.cs
- solutions/ReleaseExtras/RuntimeFiles/InstallNetFramework.bat
- solutions/ReleaseExtras/RuntimeFiles/start-tModLoader.bat
- solutions/ReleaseExtras/RuntimeFiles/start-tModLoaderServer.bat
1) Batch files will now step people through manual portables installation when it fails to install.
2) Removed dependency on Vanilla finder.HasItem to determine if CreateItem() vs. UpdateItem(). We won't create new items if the item has already a publish ID assigned (reduces dupes)
3) added a few lines of logging around create and update
4) removed ending CreateItem result if WorkshopAgreement not done so that UpdateItem runs.
5) Reworked dependency on writing to manifest out of UpdateItem to be checked before doing anything.
6) Removed defunct code, refactored ForceCallbacks method to simplify for later.
7) Passed the HasUpdate bool to try and force downloading the Workshop Item again, even if Steam doesn't think there is an update.
> [1.4 Support bugs] Many Batch and Workshop Cleanup

- ExampleMod/Common/Players/ExampleKeybindPlayer.cs
- ExampleMod/ExampleMod.cs
- ExampleMod/Old/ExampleMod.cs
- ExampleMod/Old/ExamplePlayer.cs
This commit adds the random buff keybind that was present in 1.3 ExampleMod to 1.4 ExampleMod
I've taken the approach to create a separate player class for this as has been done for luck and inventory, let me know if this is not desirable.
I'm not sure if I should create a separate class for registering the keybind that would also have an unload method that would set the static field to null, kind of like what is currently done for the recipes.
As a side note, I'm getting the warning that ExampleMod did not fully unload whenever I reload the mods, but I was getting this warning even before my commit so I'm not sure if I should be concerned about that.
This is my first PR on this project so please be kind if I've forgotten anything or missed the mark on some of these changes, and advise as …
> Add keybind to 1.4 ExampleMod

- patches/tModLoader/Terraria/Recipe.Extensions.cs
- patches/tModLoader/Terraria/Recipe.cs.patch
RecipeIndex was inaccurate, this PR aims to fix it (and I think this time will be the one).
Added the RecipeIndex shift in the three methods switching the recipes.
Some part of the code was hard to read so I removed all the parts using the now useless UseX.
As RecipeIndex allows to directly find the Recipe, I used it in the Recipe.RemoveRecipe instead of checking every recipe to find it.
> 1.4 RecipeIndex fix (again)

- patches/tModLoader/Terraria/ModLoader/Engine/InstallVerifier.cs
Windows is steamapps
Mac is SteamApps.
This check occurs prior to dealing with GoG pathfinding, so eliminates a large amount of overhead and possible issues for Steam installations
> Make SteamApps path check case insensitive

- patches/tModLoader/Terraria/ModLoader/LocalizationLoader.cs
hjson translation with $parentVal doesn't work
I added the replacement from ".$parentVal" to "" on the translation creation
The implementation could maybe be a bit cleaner but that's the simplest
> parentVal translation fix

- patches/tModLoader/Terraria/DataStructures/PlayerDrawHeadSet.cs.patch
- patches/tModLoader/Terraria/DataStructures/PlayerDrawLayers.tML.cs
- patches/tModLoader/Terraria/DataStructures/PlayerDrawSet.cs.patch
Player head is drawn bald as in issue: https://github.com/tModLoader/tModLoader/issues/1657
This behaviour happens every time a head only player is drawn
Added to `PlayerDrawSet.HeadOnlySetup` the hair frame setup like in `PlayerDrawSet.BoringSetup`.
The fix could be better "included" as having a `HeadOnlySetup` being called at the beginning of `BoringSetup` forcing every update on head rendering setup will propagate to both and have less code.
But atm it is not reasonable because the functions seems to be in a way that makes it "edit intensive", need more research on vanilla decompiled code to figure out if it is feasible.
> [1.4] Fixing hair frame missing on HeadOnly setups

- patches/tModLoader/Terraria/Audio/SoundEngine.cs.patch
- patches/tModLoader/Terraria/Localization/Content/en-US/tModLoader.json
- patches/tModLoader/Terraria/ModLoader/SoundLoader.cs
Currently, an error isn't shown to user until SoundLoader accesses the null SoundPlayer object. 
This PR readjusts the error to be notified when it is first detected (SoundEngine.Initialize) and extend SoundEngine.IsAudioSupported in to SoundLoader to prevent it from throwing errors.
> Extend SoundEngine.IsAudioSupported to SoundLoader

- patches/tModLoader/Terraria/ModLoader/Engine/TMLContentManager.cs
https://github.com/tModLoader/tModLoader/issues/1691
Fixing it before `Main` instantiation was not reasonable because asset direcotries are not calculated yet (Steam Terraria needs it's own identification etc...).
So in `TMLContentManager` before any operation I added a Windows only check and move in-place of the files cases.
The fix contains a constant array (not "really" constant because C#...) of possible stale assets (with extension) in their valid expexted cases, it worked for me, and was all described in the issue, if any new stale case issue arises there will be additions to this array.
`gore_240` is present in `ResourcePacksDefaultInfo.tsv` so it's probably still shipped as lowercase? (probably not used or some pre build script was not run in the vanilla build, sure if used the …
> Checking case of known stale assets

- patches/tModLoader/Terraria/Main.cs.patch
Now it properly reflects being opt-in tmodloader setting that changes away from vanilla behavior.
Should decrease the frequency of reports of #1661
> Fix Remove Forced Minimum Zoom setting being inverted

- patches/Terraria/Terraria/Net/Sockets/SocialSocket.cs.patch
- patches/tModLoader/Terraria/Social/Steam/NetClientSocialModule.cs.patch
- patches/tModLoader/Terraria/Social/Steam/NetServerSocialModule.cs.patch
- patches/tModLoader/Terraria/Utils.cs.patch
1) Fix Platform not supported Error from BeginInvoke
2) Fix Steam 'connect_lobby' argument for both when called, and passing argument
3) Add logging of what the LobbyID is/was for Servers
This does NOT mean that Steam Multiplayer is working, but is an improvement in terms of fixing some of the bugs around it.
A future PR will still be needed to fix Steam Multiplayer
> [1.4 Alpha] Fix Steam Connect_Lobby argument

- patches/tModLoader/Terraria/Social/Steam/WorkshopHelper.TML.cs
There is currently a gap where if no callback is received (which shouldn't happen as either Game Server API or SteamAPI will have initialized if its reaching such a code point, and thus callbacks must be delivered), but nevertheless, doesn't hurt to make sure the failure mode is caught instead of an infinite loop.
> Add Error Handling 'no callback received' Failure Mode

- patches/tModLoader/Terraria/Netplay.cs.patch
- patches/tModLoader/Terraria/Properties/launchSettings.json.patch
- patches/tModLoader/Terraria/Social/Steam/NetServerSocialModule.cs.patch
- patches/tModLoader/Terraria/Social/Steam/WorkshopHelper.TML.cs
Bug #1707 fix
- Remove influence of InstallVerifier so the GameServer doesn't accidentally init on Steam Server
- Add error-handling where logging/errors should have been handled in vanilla
- Add a correctly configured Steam Server launch configuration for testing purposes
> [1.4] Patch Steam Multiplayer

- patches/tModLoader/Terraria/Terraria.csproj.patch
- setup/setup.csproj
MonoMod.Detour was updated after our last update of TerrariaHooks to stop erroring on missing Mono.Posix when not using Mono. This in particular has shown up in every Mac logs, so it would be helpful to eliminate irrelevant errors. 
Updated Terraria hooks by arunning a new debug build for 1.4, than updateing the version of both HookGen & Detour in Setup and tmod.csproj respecitvely. Than ran hookgen and  diffed, than rebuilt and checked that a few mods are still working (Better Mod List, Magic Storage, and ExampleMod)
> Update TerrariaHooks to remove Posix Mono error on Mac

- patches/tModLoader/Terraria/Main.cs.patch
Currently, rendering performance on well lit areas (such as those of the Builder's Workshop map in #1788 ) greatly hammer the frame when renderCount = 3 while in Colour lighting mode. 
This PR spreads out some of that load, saw an up to 15% improvement in average fps from this change in well-lit areas
Spread out load away from the frames when renderCount is 3 on Colour lighting.
This brings all frames above 60 fps on release builds, and improves debug build fps by ~10-15%
Ideally, I'd like to fix the RenderX methods to be better, but didn't see anything obviously wrong to move forward with such a direction
Currently the legacy lighting operates on a 5 frame loop for rendering. Each frame render Count is incremented and than wraps. 
The selection of at which renderCount value at which to …
> [1.4] Minor Tweak to slightly improve rendering performance

- patches/tModLoader/Terraria/GameContent/Events/Sandstorm.cs.patch
- patches/tModLoader/Terraria/Main.TML.cs
- patches/tModLoader/Terraria/Main.cs.patch
1. Make `Sandstorm.Start/StopSandstorm` public, add documentation
2. Document `Main.Start/StopRain`, add helper method (`Main.SyncRain`)
1. Modders will not need to use reflection to invoke the sandstorm methods
2. Documentation is always nice, the added method does not modify vanilla in any way either, only exists for modder convenience to use alongside `Main.Start/StopRain`
Mirsario suggested directly modifying the `Main.Start/StopRain` to automatically sync when invoked. This however would require more changes to be made, especially regarding how the journey mode rain slider works.
```cs
if (!Sandstorm.Happening) {
Sandstorm.StartSandstorm();
}
if (Main.netMode == 2 && Main.maxRaining == 0) {
Main.StartRain();
Main.SyncRain();
}
```
No
> [1.4] Document/publicise some weather methods

- patches/tModLoader/Terraria/Recipe.cs.patch
Recipe methods 'ProcessGroupsForText' and 'AcceptedByItemGroups' were (mistakenly?) made internal
Made them public again
> [1.4] Make 'ProcessGroupsForText' and 'AcceptedByItemGroups' public

- ExampleMod/Content/NPCs/MinionBoss/MinionBossBody.cs
- ExampleMod/Content/NPCs/MinionBoss/MinionBossMinion.cs
In MinionBossBody.cs and MinionBossMinion.cs, it is falsely stated that if an enemy is immune to poison, it should also be immune to venom. This is not the case in 1.4.1, since venom was renamed to 'Acid Venom', and a significant amount of enemies had their immunity to it removed.
This PR simply removes the immunity from MinionBossBody and MinionBossMinion.
I don't think so.
> [1.4] (ExampeMod) Remove Acid Venom immunity from MinionBossBody and MinionBossMinion

- patches/tModLoader/Terraria/ModLoader/Core/TmodFile.cs
- patches/tModLoader/Terraria/ModLoader/Mod.cs
The `TmodFile.GetFileNames()` and `Mod.GetFileNames()` methods.
Currently, there is no way to get the name of every file in your mods `TmodFile`. Getting and querying every file name is invaluable for dynamic file reading, and lets you avoid having to hardcode every file path you want to read.
No. `Mod.Assets` and every other asset loading related method only cares about files it considers assets - that is, files with an existing asset reader. This is used to get every file name in the `TmodFIle`, not every asset file name.
Any custom data driven feature - say, data driven simple material items - requires you to know the name of every file with the data that you need to load. This could be done by hardcoding a list of file paths, but it's much more elegant to autoload all the files in a …
> TmodFile.GetFileNames() and Mod.GetFileNames()

- patches/tModLoader/Terraria/ModLoader/ModContent.cs
- patches/tModLoader/Terraria/ModLoader/MonoModHooks.cs
- patches/tModLoader/Terraria/ModLoader/UI/Interface.cs
- patches/tModLoader/Terraria/Program.TML.cs
- patches/tModLoader/Terraria/Program.cs.patch
- solutions/ReleaseExtras/RuntimeFiles/InstallNetFramework.bat
- solutions/ReleaseExtras/RuntimeFiles/InstallNetFramework.sh
- solutions/ReleaseExtras/RuntimeFiles/start-tModLoader.bat
- solutions/ReleaseExtras/RuntimeFiles/start-tModLoaderServer.bat
1) Cleanup MonoModHooks file to have less extra stuff going on
2) Improve logging surrounding MonoModHooks
3) Fix Beta Welcome message conflicting with the FirstLaunch Message for first time users
4) Add the COM_Plus variable in to tmodloader instead of start files, fixes #1718
5) Cleanup the manual install .NET instructions a bit
6) Add a "sysdotnet" launch param for start-tmod.bat files so can use a system dotnet in the event that portables just won't work (or w/e other reason).
7) Make InstallNetFramework.bat able to be run independent to start scripts again.
> Many Misc Tiny Fixes

- patches/tModLoader/Terraria/ModLoader/ModContent.cs
- patches/tModLoader/Terraria/ModLoader/MonoModHooks.cs
- patches/tModLoader/Terraria/ModLoader/UI/Interface.cs
- patches/tModLoader/Terraria/Program.TML.cs
- patches/tModLoader/Terraria/Program.cs.patch
- patches/tModLoader/Terraria/Terraria.csproj.patch
- setup/setup.csproj
- solutions/ReleaseExtras/RuntimeFiles/InstallNetFramework.bat
- solutions/ReleaseExtras/RuntimeFiles/InstallNetFramework.sh
- solutions/ReleaseExtras/RuntimeFiles/start-tModLoader.bat
- solutions/ReleaseExtras/RuntimeFiles/start-tModLoaderServer.bat
1. Cleanup MonoModHooks file to have less extra stuff going on
2. Improve logging surrounding MonoModHooks
3. Fix Beta Welcome message conflicting with the FirstLaunch Message for first time users
4. Add the COM_Plus variable in to tmodloader instead of start files, fixes [1.4 Windows] StackOverflow when breaking 128+ gravity affected blocks in a vertical stack #1718
5. Cleanup the manual install .NET instructions a bit
6. Add a "sysdotnet" launch param for start-tmod.bat files so can use a system dotnet in the event that portables just won't work (or w/e other reason).
7. Make InstallNetFramework.bat able to be run independent to start scripts again.
8. Update MonoMod.Detour to latest version, includes fix for Mod unloading on release builds
> Misc tiny fixes

- patches/tModLoader/Terraria/ModLoader/Logging.cs
- patches/tModLoader/Terraria/Program.TML.cs
- patches/tModLoader/Terraria/Program.cs.patch
- solutions/ReleaseExtras/RuntimeFiles/InstallNetFramework.sh
.NET doesn't appear to respect its own environment variable when set after launch using the SetEnvironmentVariable method its docs recommend.
Neat.
EDIT----------------------------------------------
Thanks to DarioDaf, the following info explicitly shows that it this env var has to be set pre-launch:
https://github1s.com/dotnet/runtime/blob/HEAD/src/coreclr/pal/src/init/pal.cpp#L271
> Repair MinStackSize on Mac

- patches/tModLoader/Terraria/ModLoader/ItemLoader.cs
- patches/tModLoader/Terraria/ModLoader/ModItem.cs
- patches/tModLoader/Terraria/ModLoader/ModSystem.cs
- patches/tModLoader/Terraria/ModLoader/ModTileEntity.cs
- patches/tModLoader/Terraria/ModLoader/NPCLoader.cs
- patches/tModLoader/Terraria/ModLoader/PlayerLoader.cs
- patches/tModLoader/Terraria/ModLoader/ProjectileLoader.cs
Temporary patch to avoid loading mods with Save and Load "the old way" because this will result in data being not saved on unload and so mod data being removed
> [1.4] Avoid wipe of mod data on SaveData/LoadData

- patches/tModLoader/Terraria/ModLoader/IO/ItemIO.cs
- patches/tModLoader/Terraria/ModLoader/IO/PlayerIO.cs
- patches/tModLoader/Terraria/ModLoader/IO/TileIO_TEs.cs
- patches/tModLoader/Terraria/ModLoader/IO/WorldIO.cs
Made foreach loop reuse Tag when never used outside and assigned to the parent tag
> [1.4] Reusing only locally empty TagCompounds that are not assigned anywhere

- patches/tModLoader/Terraria/ModLoader/Mod.Internals.cs
ILoadable implementations with a non public parameterless constructor are ignored
Allowed non public constructors
No
> Allow non public constructor on ILoadable implementations

- ExampleMod/Content/Items/ExampleDye.cs
ExampleDye shader loading is missing `ImmediateLoad`
Added `ImmediateLoad`
No
> [1.4] EM ExampleDye shader fix

- patches/Terraria/Terraria/Main.cs.patch
- patches/tModLoader/Terraria/Main.cs.patch
Previously, a commit was made against our fork of FNA to add a "headlessMode" bool to the Game constructor. (https://github.com/FNA-XNA/FNA/commit/3907b989a7b3494cc974618b9128b9772009bc1f)
This actually implements its use on our side, as it seems that was missed.
Whether the headlessMode is functional in FNA end, I can't say, but this helps to get in right direction at least.
> Actually use the headless argument added to XNA.Game()

- patches/tModLoader/Terraria/ModLoader/Default/UnloadedTileEntity.cs
- patches/tModLoader/Terraria/ModLoader/ModTileEntity.cs
https://github.com/tModLoader/tModLoader/issues/1813
Replaced unnecessary ValidTile method with existing IsTileValid method.
This will force mods to override the correct method, and not have two functionally equivalent methods co-exist.
> [Mod-Breaking] Eliminate duplicate override ValidTile in favor of existing IsTileValid

- patches/tModLoader/Terraria/DataStructures/TileEntitiesManager.TML.cs
- patches/tModLoader/Terraria/DataStructures/TileEntity.cs.patch
- patches/tModLoader/Terraria/ModLoader/ModTileEntity.cs
ModTileEntity.PreGlobalUpdate and ModTileEntity.PostGlobalUpdate not being called
Fixed a LINQ query
No
> [1.4] Fix ModTileEntity.GlobalUpdate methods not being called

- patches/tModLoader/Terraria/ModLoader/ModTileEntity.cs
ModTileEntities don't get placed in MP
`Type` is functionally equivalent to `_myEntityID` of vanilla TileEntities and only gets assigned once per TileEntity
`type` is the id of a placed TIleEntity
Before a TE is placed `type` is by default 0, which isn't a valid ModTileEntity id
Fixed the typo
Voodoo
> [1.4] Fix ModTileEntities not being placeable in MP

- patches/tModLoader/Terraria/WorldGen.cs.patch
`tile.type` is passed as the wall type insead of `tile.wall`
Changed `tile.type` to `tile.wall`
Nope
> [1.4] Fix wrong argument to `WallLoader.KillWall`

- patches/tModLoader/Terraria/Player.TML.cs
- patches/tModLoader/Terraria/Player.cs.patch
- patches/tModLoader/Terraria/Projectile.TML.cs
- patches/tModLoader/Terraria/Projectile.cs.patch
`Player.QuickSpawnItem` now returns the index of the spawned item
Added Direct variants to `Player.QuickSpawnItem`
Allows modifying the data of the spawned item
Add more arguments to `Player.QuickSpawnItem`
```cs
Item item = player.QuickSpawnItemDirect(ItemID.Zenith); // or `Main.item[Player.QuickSpawnItem(ItemID.Zenith)]`
item.prefix = PrefixID.Legendary;
```
None
> [1.4] `Player.QuickSpawnItem` return item index

- patches/tModLoader/Terraria/Map/MapHelper.cs.patch
1.4 added a `wall < 316` check where wall map data is calculated, causing modded walls to never appear on the map, as per #1938. This PR fixes it by changing it to the tml upper bound instead.
> [1.4] Fix modded walls not appearing on the map

- solutions/ReleaseExtras/tModLoader-mono
On non-standard `LD_LIBRARY_PATH` environment values (such as NixOS) the provided tModLoader mono launch script will not locate essential libraries (PulseAudio, xinput, etc.) and will be unusable.
Instead of forcefully setting `LD_LIBRARY_PATH` to `lib:lib64` (which would load ./lib/, /lib/, ./lib64/ and /lib64/) it's instead added to the path with `$LD_LIBRARY_PATH:lib:lib64`
Not that I know of. This is how environment values that contain paths are usually added to in Unix shell scripts, and the current version only works by accident (I wasn't even aware you could load /lib with just `lib`).
This may also need similar fixes on MacOS, but I do not have a Mac PC so I cannot personally test any changes.
> Fix mono launch script on non-standard LD_LIBRARY_PATH
